### ISSUE TITLE
Add `concatMap` to core

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#105]
Small pattern we see too often is code like `implode("", map(foo, list))`, especially with the newish string interpolation syntax.

We should add `concatMap` to core. The only problem is that `concatMap` is traditionally defined for lists in Haskell.

    concatMap :: (a -> [b]) -> [a] -> [b]

But we'd really like it for strings in Silver.

    function concatMap
    String ::=  f::(String ::= a) list::[a]

Mostly. It turns out there's a few uses of `foldr(append, [], map(foo, list))` too.

I'm thinking, for the moment, we should introduce these to core:

    concat :: [[a]] -> [a]
    concatMap ::  (a -> [b]) -> [a] -> [b]
    sconcat :: [String] -> String
    sconcatMap :: (a -> String) -> [a] -> String

And maybe someday if Silver gets typeclasses, we can do away with the `s-` prefixed ones.

**Comment by tedinski** [comment]
Question to answer: `concatMap` or `flatMap`?

**Comment by remexre** [comment]
* `flatMap` is used by Java, Rust, Scala, Swift, and underscore.js/lodash
 * `concatMap` is used by Haskell (although `>>=` works too)

Based on this, I think `flatMap` is a better term, although I have no actual issues with `concatMap`.

**Comment by ericvanwyk** [comment]
No strong preference - though Silver does have more Haskell influence than
anything else.  :: for has type, etc.
