### ISSUE TITLE
Vim highlighting w/ block comments

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#109]
```
{-- has the bug
-}
{- no bug
-}
```

There's an issue with `{--` as an... ermmm... comment starter? Is that what that's called? With that thing.

![2017-01-31-01 19 13](https://cloud.githubusercontent.com/assets/4196789/22455629/72225b24-e753-11e6-9da9-aa1bbca27dd9.png)
![2017-01-31-01 19 16](https://cloud.githubusercontent.com/assets/4196789/22455630/7380ad04-e753-11e6-8533-bbad07c3c2b6.png)

**Comment by TravisCarlson** [comment]
Can you confirm that the change just pushed to the [bugfix/vimhl](https://github.com/melt-umn/silver/tree/bugfix/vimhl) branch fixes this and doesn't introduce any other issues?

**Comment by ericvanwyk** [comment]
Nathan, please write a bit more in your description - specifically if this is bug in Silver or in syntax highlighting in some editor.  This is a bit too terse.

**Comment by remexre** [comment]
@ericvanwyk Sorry for the terseness; it's vim.

@TravisCarlson Looking over a couple files in ableC, this issue looks fixed with no regressions in the bugfix/vimhl branch.

**Comment by tedinski** [comment]
Looks like this was fixed, but the pull request didn't automatically close this issue.
