### ISSUE TITLE
Flow analysis confuses locals with the same names

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#113]
Not sure if this is related to #52 or not.  

If you write a production with a local, and aspect it and write a local with the same name, even in a different  grammar, then the local in the aspect production gets the same direct flow dependencies as the local in the original production.  

For example if in grammar a you have a production with a local with a dependency on an inherited attribute:
```
abstract production foo
top::Expr ::=
{
  local bar::Expr = doSomethingWithEnv(top.env);
}
```
and an aspect with the same local and equation in grammar b:
```
aspect production foo
top::Expr ::=
{
  local bar::Expr = intConst(0);
}
```
then anything using bar in the aspect has flow dependencies on top.env.

**Comment by tedinski** [comment]
It might be wise to prioritize fixing this issue (note to self), because we just wasted a lot of time over this not realizing what the root cause was!
