### ISSUE TITLE
Change to transparent prefix syntax

### ISSUE THREAD

**Issue by ericvanwyk** [melt-umn/silver#116]
Can we change the syntax for specifying transparent prefixes from
   <terminal-name> prefix with <string or terminal-name>
to
   prefix <terminal-name> with <string or terminal-name>

This looks nicer to me and also matches the prefer ... over ... syntax that is also used in transparent prefixes.

After making this change, we need to change the demos in the 'ableC_sample_projects' repo.

**Comment by ericvanwyk** [comment]
OK, markdown ate parts of what I wanted to say.

I meant,

Can we change the syntax for specifying transparent prefixes from
     terminal-name  **prefix with**  string or terminal name
to
     **prefix** terminal-name **with** string or terminal name

**Comment by tedinski** [comment]
Not even sure what you're referring to. Should that be `grammar-name` not `terminal-name`? I see this in one of those grammars:

```
edu:umn:cs:melt:exts:ableC:tables prefix with "CT";
```

I don't think I like your suggestion, since it obscures the fact that we're just listing the names of grammars to include in parser declarations.

Not listing terminals is a special case of the 'prefix' syntax though. Perhaps we could just remove the 'with' for this special case? (Or perhaps add some parens to group the modifiers?)

```
edu:umn:cs:melt:exts:ableC:tables prefix "CT";
edu:umn:cs:melt:exts:ableC:tables (prefix "CT");
-- normally things looks like this:
edu:umn:cs:melt:exts:ableC:tables prefix 'table' with "CT";
```

**Comment by ericvanwyk** [comment]
Markdown mangled my message - the second one is more clear.

My suggestion is to improve what is there now - that is what I think you
don't like.

We did this, IIRC, because it was simple enough to do and we had gone far
to long without an implementation of our transparent prefixes.

I would like specs like you suggest.

Lucas, how hard would it be to do these?

We'd also need something like
   edu:umn:cs:melt:ableC:table prefix with "CT", make default;
or something like that to take the place of the current
prefer ... over ... ;
syntax we have now for specifying this.

These are longer term solutions, however.  So I'd still like to make my
suggested changes now since this improves things, though not as much as
they could be improved...

-Eric

**Comment by ericvanwyk** [comment]
OK, I went to look at this more closely because I didn't know what Ted was talking about...

It is 
  grammar name **prefix with** string, not what I'd stated. Doh.

So, there is nothing to do.   I'm too busy to think clearly, it seems... 

Closing.
