### ISSUE TITLE
langutil lacks support for 'structured' errors

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#117]
This issue came up when working on the template extension, where if we have a template instantiation that generates a corresponding declaration with errors, we need to be able to report those errors in a nice way.  GCC will have a 'note' message at the instantiation site, followed by the errors caused at the declaration site.  Since we currently just sort all errors by location, appending warnings for the instantiation site in the list of errors still results in them showing up in the wrong place.  
One way of fixing this would be to add a `group` error constructor with a location, initial note, and list of errors to wrap.  This would be sorted by the source location, and could maybe even display the wrapped messages indented.  
We should also probably have just a general standalone 'note' constructor similar to err and wrn, for things that aren't errors or warnings but extensions may wish to report.  
Finally, we should also make Message a closed nonterminal so that extensions can specify new types of messages with custom formats, severities, etc.  This library seems like it was designed to work in this manner, but currently defining a new Message production would result in orphaned production warnings with the flow analysis.

**Comment by remexre** [comment]
Closed by 1c50ce8.
