### ISSUE TITLE
Some build.xml files should be gitignored.

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#120]
e.g. `tutorials/hello/silver-compile` creates a `build.xml` that relies on system-dependent paths. Non-generated `build.xml`s shouldn't be gitignored, though, and I'm not sure on the best approach to ignore the right ones. I can think of three approaches:

 - Ignore all generated `build.xml`s manually in the root `.gitignore`
 - Ignore all `build.xml`s in the root `.gitignore`, then unignore (with `!`) the ones that aren't generated
 - Ignore each generated `build.xml` in a `.gitignore` that's in the directory it gets generated into

**Comment by ericvanwyk** [comment]
Which ones should not be 'gitignored' ?

Do we really have some hand-written ones?

**Comment by remexre** [comment]
I've got:

```shell
$ git ls-files | grep build.xml
runtime/java/build.xml
tutorials/monto/monto-frontend-cli/build.xml
tutorials/monto/monto-frontend-gui/build.xml
```

so it might make sense to just manually unignore the `runtime/java/build.xml` one, and remove the monto tutorial for now

**Comment by tedinski** [comment]
Ah, those monto ones have been a thorn in the side of `deep-clean` for awhile.
