### ISSUE TITLE
getTime

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#121]
It'd be useful to have a `getTime` function in Silver; however, the value it returns is nonobvious: time/date handling is hard (time zones, daylight savings time, leap seconds, NTP time travel), and different languages choose different options; compare [Rust](https://docs.rs/chrono/0.3.0/chrono/#date-and-time) to [Go](https://golang.org/src/time/time.go#L30).

Should `getTime` return an `Integer` (or a `long` if that's a thing), or some custom datatype? We should probably support ISO8601 formatting, but what about other formats? I definitely need some way to get the current time (as a String?) for Monto, although as far as I can tell, it's ignored (my test case was setting the time field to `"Now O'Clock"` -- nothing broke).

If we do go with a custom datatype, what fields should it have? If using a <units> since epoch counter, what should the units be? C uses seconds, Go uses seconds and nanoseconds.

Go and Rust (and presumably other languages) also differentiate between "political time" and "physical time" (my terminology); an example is

```java
PoliticalTime politicalStart = getPoliticalTime();
PhysicalTime physicalStart = getPhysicalTime();

sleepSeconds(5);

PoliticalTime politicalEnd = getPoliticalTime();
PhysicalTime physicalEnd = getPhysicalTime();
```

`physicalEnd - physicalStart` is guaranteed to be 5 seconds (plus or minus the OS scheduler, etc), while
`politicalEnd - politicalStart` could be any of:

 * 5 seconds (no weirdness)
 * 4 seconds (leap second)
 * 6 seconds (leap second)
 * -(59 minutes 55 seconds) (timezone change or daylight savings)
 * 60 minutes 5 seconds (timezone change or daylight savings)
 * 76 years 5 months 4 days 3 hour 2 minutes 1 second (NTP fun)
 * etc.

So `PoliticalTime - PoliticalTime` isn't a (well-) defined operation. On the other hand, it's then usually not supported/more annoying and slower to go `PhysicalTime -> String`.

How much of this should be implemented in Silver, if any? It's totally also possible for me to add the time field to the Monto response object from within Java, just in case we don't want to deal with this (now).

**Comment by tedinski** [comment]
I wouldn't bother with anything fancy in Silver at all.

Is this something that could have been handled Java-side for Monto? I think the best solution is for Silver to be quite oblivious to time, if possible.

Right now we have `fileTime`, it returns an `Integer` (I suspect this is unix time.) We could maybe add another IO function that returns the current time (also `Integer`, so those are comparable) and maybe a minimal function for trying to convert an `Integer` into a human-readable string of some sort. It sounds from your description that this would be the minimum necessary?

**Comment by remexre** [comment]
Yeah, I could implement it Java-side or with `getTime` and `toISO8601String` (or a name that isn't bad); either would be sufficient.

**Comment by remexre** [comment]
This is implemented Java-side for Monto; should I close this?
