### ISSUE TITLE
Should we have both ParseResult.parseError and ParseResult.parseErrors?

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#127]
(See #126)

Right now, `ParseResult` has a `parseErrors :: String` attribute; #126 adds a `parseError :: ParseError` attribute. Seeing as the `parseErrors` attribute is just `parseError.parseErrors`, should `parseErrors` be removed from `ParseResult`?

**Comment by tedinski** [comment]
I'm not opposed to helpers, and removing it would break any existing code that uses it, so eh, let's keep it?

**Comment by remexre** [comment]
Ok, fine by me.

**Comment by ericvanwyk** [comment]
Sounds fine to me too.  I asked Nathan to post this as an issue.  It would
be nice to clean up, but it is very low on the priority list.

**Comment by tedinski** [comment]
Yeah, if we wanted to bother fixing up all users of `ParseResult` I'd probably want it to be because we rename `Either, left, right` to `Result, ok, fail` and changed ParseResult to just be:

```
type ParseResult<a> = Result<a ParseError>
```

But of course doing this means quite a lot of work fixing up old code.
