### ISSUE TITLE
silver:langutil:pp has name collisions with core

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#146]
I'm branching this issue off of #139 

After thinking about it for a bit, I'm unhappy with this library causing problems like this.

NOTE: In the long run, I expect we'll have some context-based name resolution, such as issue #31 suggests. Adopting this approach will ultimately require modifying lots of code anyway though.

I think I'd like to rename the function in the `pp` library. `ppImplode` and `ppConcat` I guess. I think it's kinda silly that we have a library that's so hard to use properly that we haven't done so at all.

AFAIK, the users of this library are AbleC, and the simple tutorial, so it's just those that need fixing. (Dunno, does AbleP use it? Possibly old svn simple grammar?)

Thoughts?

**Comment by remexre** [comment]
I'm in favor of this; it's always been kind of weird to me that we always had to do an import-as for something used so widely.

**Comment by krame505** [comment]
Yeah, I guess that is for sure better than renaming `core:concat` to `concatList`.  But to be consistant with our naming conventions, shouldn't the type be a suffix (i.e. `implodeDocument` or `implodePP`), although that would break a lot of things.  The other option is to leave it as-is, and take an approach like treemap, where we require (or recommend) that it be imported with a prefix.  Whatever we do, we should also think about what changes will need to happen when we introduce type classes or a better method of name resolution some day.  

We have already finished refactoring ableC to use the renamed imports, not sure about the other stuff though.  At least I don't think anyone is using 'pp:implode' without renaming right now.

**Comment by ericvanwyk** [comment]
Don't other languages require some module name use when two modules being
used declare the same name?  Is qualifying pp when importing it so bad?

**Comment by tedinski** [comment]
It's apparently bad enough that, despite recommending it, I don't think we actually `import silver:langutil:pp as pp` anywhere. It's too annoying to write code that way. This is part of the reason I'm fond of issue #31. It'd make a lot of things a lot nicer to write. But, time and effort. Maybe someday.

For the moment, I think every user does `import silver:langutil:pp with implode as ppImplode, concat as ppConcat`. I'm proposing just doing that renaming and removing the need to do this.

**Comment by ericvanwyk** [comment]
This contextual name lookup would be nice.

My objection to ppImplode and ppConcat is that is just seems wrong.  But
naming them implode and concat isn't much better, at least in practice.  So
I'm happy to go along with this.

**Comment by tedinski** [comment]
It is wrong, really. But I think the principled way is the contextual name lookup stuff, and if we ever did that, we'd have the opportunity to rename things anyway, because we'd have to rewrite a bit of code anyway.

We'd probably see `ppImplode(sep, list)` become `list.join(sep)` (assuming we had dot-functions, too.)
