### ISSUE TITLE
Running the flow analysis from the Eclipse IDE

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#167]
It would be extremely useful to have a way of running the flow analysis from the Eclipse IDE.  Is there an easy way of enabling this?

**Comment by krame505** [comment]
Would it be possible to be able to set a flag in project.properties, to enable or disable running the analysis?

**Comment by ericvanwyk** [comment]
Is this really that useful?  Having an open terminal window for this seems
easy enough.  Besides, we're moving towards Monto for IDE-like things.
This could be something to try to incorporate into that, but I'm not
enthused about more time spent on developing the existing Eclipse IDE.

**Comment by remexre** [comment]
Monto's commands support arbitrary actions, so Jason[1] could probably add a button to the Eclipse plugin for flow analysis when he makes the "nice" Eclipse-Monto plugin. If you want it to run per-build, that's relatively easy to incorporate as a configuration option (which are runtime settable) for Silver's Monto service.

[1]: I couldn't @mention him, which reminds me -- we need to add the undergrads to this GitHub org. I don't have privileges to.

**Comment by krame505** [comment]
I was trying to fix a bunch of flow errors that showed up as a result of
some of the fixes Ted made to the analysis, and yes, it really is a pain
when confronted with a wall of error messages.  There are a fair number of
flow issues in ableC that will pop up when we correctly set the explicit
flowtypes, and having this will save a lot of time when that process does
happen.
Unlike other changes to the IDE, this seems like it should be something
that doesn't require a lot of in-depth refactoring or major modifications.
I realize the Eclipse IDE will be going away at some point, but given the
performance and stability issues Nathan has been seeing that may require a
major redesign of Monto, I don't know how long it will be before the new
IDE is usable enough to replace what we have now.

Lucas Kramer

**Comment by ericvanwyk** [comment]
Lucas,

I agree this would be nice, but who wants to take on this non-trivial task?

Nathan has highlighting and error checking working in Emacs now - so adding
the --warn-all flag will get us somewhere to what you want.

-Eric

**Comment by krame505** [comment]
Errors in monto-mode are still just shown in a seperate buffer though,
right?  Or did Nathan get error highlighting working?
Anyway this isn't something that needs to be done right this minute, just
something that would be really good to have before whoever dives into
annotating ableC flowtypes does so.

Lucas Kramer

**Comment by ericvanwyk** [comment]
Yes, it is still just has errors in a buffer.  But I don't see how this is
so bad.

If you're volunteering to do this work, great! :)

-Eric

**Comment by krame505** [comment]
Not necessarily bad, but not much better than running in a terminal.

If eventually I end up being the one to make these fixes for ableC, I will
probably end up implementing this.  But that is a ways down the road, after
I finish the tutorials.

Lucas Kramer

**Comment by remexre** [comment]
Right now, Silver's server only actually gives syntax errors; I've been rather wrapped up in writing the emacs part for a while. I'll put the semantic errors in tomorrow; the Silver driver was confusing enough that I stopped once I had the minimum viable demo.

Errors *should* be both highlighted with an underscore (yeah, not hugely visible) and shown in a separate buffer. I'll make the separate buffer optional and change the mark to be more visible tomorrow too; those are quick changes.

The larger issue is that monto support is still a branch; I can try to merge it on Monday if people want to be using it.

**Comment by ericvanwyk** [comment]
I think this progress on the Monto side will get us where you, Lucas, want
to go quicker than anything else.

Nathan, we should merge, but not until it is ready to do so.   I don't
think Lucas is hoping to attack these problems immediately.

Thanks guys -

-Eric

**Comment by krame505** [comment]
Fixed, closing.
