### ISSUE TITLE
Invalid generated code after error

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#173]
Both @AnkitSiva and @zozee9 have run into this (and I never have), so it also might be a macOS bug?

When running a JAR created by `silver --clean grammarName`, it complains that `NIOVal` is missing in a JNI error. After this, the `Init.java` created for a grammar is missing the `count_syn` and `count_inh` variables. After `./deep-clean -delete all; ./deep-rebuild`, the problem's gone (at least temporarily).

They've both `./update`'d since then, and haven't encountered it since. If this was fixed by #171, close this. (I'm not sure what the bug #171 fixes is)

**Comment by tedinski** [comment]
It's entirely possible it was #171. Let me know if it re-occurs, otherwise, let's close this in a week or two.

**Comment by tedinski** [comment]
Think we should close this?
