### ISSUE TITLE
sv-serve has no way of setting the stack size

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#203]
We basically don't have a way of specifying the stack (or, for that matter, the heap) size when launching `sv-serve`.  The easiest fix is probably to just bump up the defaults in `sv-serve`...
This is a blocking issue for https://github.com/melt-umn/ableC/pull/68, since the increased stack usage for the generated builtins is causing some of the ableC tests to crash.  @tedinski comments?

**Comment by krame505** [comment]
Wait, it looks like ableC isn't actually even using nailgun for the expected results tests run by Jenkins?  Anyway, some of the ableC tests that I disabled were still running out of stack space when called via nailgun, so I'm leaving this open for now.

**Comment by tedinski** [comment]
Sounds sensible to me.
