### ISSUE TITLE
Default equations don't have flow types checked

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#218]
For the following program
```
autocopy attribute inh::Integer;
synthesized attribute ref::Decorated Foo;

nonterminal Foo with ref, inh;
flowtype Foo = decorate {inh}, ref {};

aspect default production
top::Foo ::=
{
  top.ref = top;
}
```

I would expect to see a flow error on the line `top.ref = top;` since the use of top as Decorated implicitly requires `inh` to be provided.  Further, the issue isn't with the `flowtype` spec because
```
abstract production foo
top::Foo ::= i::Integer
{
  forwards to if i == top.inh then error("") else foo(i + 1);
}
```
raises the expected error about the implicit forward copy equation exceeding the flow type.  

I'm not sure whether this is a known bug, but I thought I'd report it just in case.

**Comment by tedinski** [comment]
The root cause here is that default equations don't have their flow types checked at all.

This is new obligation since we introduced `flowtype` declarations. Used to be, defaults couldn't be wrong.

Gonna change the title of this bug.
