### ISSUE TITLE
Have Jenkins build downstream projects on a branch with the same name, if possible

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#220]
This is similar to what we do in ableC for building extensions.  Needed before I can merge #217.  
I took a stab at implementing this in feature/jenkins, but for some reason `env.BRANCH_NAME` contains unconverted slashes, which trips up `melt.doesJobExist`.

**Comment by tedinski** [comment]
I'm going to start committing to that branch to fix things up.

Do you have any idea why silver develop failed (ableC failed in the testing? the expected results changed?)

**Comment by krame505** [comment]
Something seems to have gone wrong with nailgun, maybe?  The output says that all the ableC tests failed.  I'm trying it again, just in case it was one of those random crashes from building too many things at once.  

Also as an aside I'm going to move the ableC tests to immediately after the build phase (instead of after building the extensions) - these are fast-ish and there is no need to waste time building all the extensions first if we broke something in the tests.

**Comment by krame505** [comment]
Looks like it was just an issue with nailgun glitching out randomly, my rebuild of develop with no changes worked.

**Comment by krame505** [comment]
Ah, we need one other thing with this as well: downstream projects (ableC) should also try to build a using a Silver branch with the same name (including the appropriate jars), when possible.  Not sure exactly how to do this (or even how ableC is checking out Silver in the first place right now) - thoughts?

**Comment by tedinski** [comment]
The only thing I can think to do is maybe we could adopt a convention of recognizing `[no ci]` in commit messages, and aborting the build if so. Then at least you could avoid triggering builds when committing changes to these branches, and manually go run the upstream build instead. Or something like that.

Everything else I can think of at the moment seems too complicated.

**Comment by krame505** [comment]
But then you wouldn't be able to ever manually trigger a build of that ableC branch. Also ableC extensions depending on that ableC branch would always fail... Ugh. Why couldn't we handle this the same way as checking out an ableC branch when building extension branches?

**Comment by tedinski** [comment]
Silver is bootstrapped and needs jars, so that's a big difference.

My inclination here is that this is all just fine. We shouldn't be making breaking changes to Silver that require downstream changes that often, and if it's awkward to deal with (but can be dealt with) that's okay with me.

Anyway, what's the status of things here? I see red trying to build the reflection branch still, looks like a problem building AbleC with your `pps` change. What's up?

**Comment by krame505** [comment]
Ah, I suppose that would be reasonable, if these downstream branches are typically quick fixes and not used for long-term development.  The `[no ci]` in commit messages feature would still be useful though.  

I should be able to merge this today, assuming no further issues.  Currently the corresponding changes in ableC are on the `feature/langutil` branch, but I will rename this to `feature/reflection` so Jenkins sees this and passes.  Once the Silver `feature/reflection` branch builds I will merge.

**Comment by krame505** [comment]
Whoops, forgot to actually merge the Jenkins changes into my branch... let's try that again.

**Comment by krame505** [comment]
Since what I originally proposed in this issue apparently isn't feasible, I'm closing this.
