### ISSUE TITLE
gitbot not running?

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#229]
Anyone have any ideas why gitbot might not be running its crontab?

```
% ls -ld /export/scratch/gitbot-deletable*
drwxr-xr-x 6 gitbot gitbot 4096 Jul 11  2016 /export/scratch/gitbot-deletable-cache/
-rw-rw---- 1 gitbot gitbot    0 Mar 13 22:07 /export/scratch/gitbot-deletable-timestamp
```

Mar 13 was when I manually ran it myself. I forget what it was saying before that. I think Feb 23 or something like that.

I'm going to tweak its script a bit and see if I can't get some more debugging output.

**Comment by ericvanwyk** [comment]
Hmm, no idea.  Feel free to change what needs fixing.

**Comment by tedinski** [comment]
Closing -- this appears to be a crashed cron process on coldpress. I notified systems.
