### ISSUE TITLE
Jenkins transition status

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#230]
I've managed to forget where I'm at, so I clearly need to write this down.

Remaining tasks:

* [x] https://github.com/melt-umn/ableC/issues/88 AbleC extensions build quicker now. Maybe still parallelize tutorial building?
* [x] Add Jenkinsfile to Oberon0
* [x] Move AbleJ to github
* [x] Move AbleP to github
* [x] Handle "META II" stuff from Adventium we'd like to ensure still builds. Perhaps we put this on our UMN github?
* [x] Move RING to github. @ericvanwyk any thoughts on getting in touch about this?
* [x] SVN grammar: `grammars/edu/umn/cs/melt/simple` any thoughts on what we want to do with this?
* [x] SVN grammar: `grammars/edu/umn/cs/melt/MATLAB` likewise?
* [x] Delete all stale old-style jobs from Jenkins
* [x] Silver should check if branch job exists before trying to copy artifacts from it. otherwise, build fails
* [x] Fix legacy early deploy logic in Silver Jenkinsfile
* [x] Lift "build same branch" logic into shared library
* [x] Lift into library the "try node catch handle finally notify" pattern
* [x] Anything to do about old branches with stale jars? Maybe just a shorthand for rerunning with default jars
* [ ] Updated version of nailgun, placed on coldpress locally, so NFS can't fail builds?
* [x] Use `currentBuild.description` to note special things about a build.
* [ ] Track down whether we're carrying around unnecessary jars?
* [x] Move melt website automation to Jenkins
* [ ] Generate eclipse update site automatically.
* [ ] Convince systems to expose Jenkins somewhere like `melt.cs.umn.edu/jenkins/`

Other stuff:

* https://github.com/melt-umn/jenkins-lib/issues/6 to add `[no ci]` tag to commits, not planning on doing this soon

**Comment by krame505** [comment]
As far as I can tell, the remaining items here have been obsoleted by the move to foundry, and the eclipse update site probably isn't important since I am often re-building the IDE using various unstable feature branches.  Closing this.
