### ISSUE TITLE
Existing flow errors in the Silver compiler

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#237]
...and what to do about them. Eventually.

* [x] any error involving `givenNonterminalType`

For `DclInfo`, attribute and annotation occurrences use this inherited attribute as an argument for accessing `typerep`, but everything else that uses `typerep` does not. This confuses the heck out of the flow analysis. The _correct_ solution is to have different types for different kinds of declaration, but this is issue #3 and not likely to get fixed soon. A short-term solution would be to break this into two synthesized attributes. Leave `typerep` for other declarations, and introduce `typerepFor :: (Type ::= Type)` for use with occurrences.

* [x] "Synthesized equation `errors` exceeds flow type..."

Likely fixable simply by introducing `flowtype` declarations to Silver.

* [x] "Forward equation exceeds flow type..." and "Implicit forward copy equation for attribute..."

Likely the same issue. Just inferred permitted inherited dependencies that are too small, so extensions are overly constrained. Some of these are likely issues with how we've overly-factored out the Silver compiler grammars, too. (Which is to say, inference should handle them but they're implemented as "extensions" not built-in.)

* [x] "Implicit forward copy equation for attribute `pp` in production `testforagdcl`/`propagateOne` exceeds flow type..."

Likely a bug that needs fixing, actually!

* [x] "Local contribution (${var} <-) equation exceeds flow with: `config`..."

All of these have one root cause. This is a problem where we don't have a way (I think? You'd think I'd remember since I implemented it, but nope.) to specific flow types for production attributes within a production.

* [x] "Orphaned production: terminalModifierFont, lexerClassModifierFont, termFont, syntaxFont, lexerClassFont"

Fonts were implemented in a quick and dirty way. The best solution to this problem would be to complete our old effort to no longer generate IDE projects, and instead just generate sufficient support within normal silver jars that a separate IDE project library can make use of. This would eliminate fonts from Silver, since those would become an external concern.

* [x] "attribute `unparse` missing equation for production `txtLoc`" Minor bug.
* [x] "`warnings`/`nilConfig` in `extension/doc/core`" Minor bug.
* [x] "Orphaned equation: `syntaxAst`/`parserSpecs`/`flowDefs` in production `interfaceRootSpec`

This is an old problem we didn't have an easy solution to. Needs re-investigation, can probably be solved somehow now.

**Comment by krame505** [comment]
> This is a problem where we don't have a way (I think? You'd think I'd remember since I implemented it, but nope.) to specific flow types for production attributes within a production.

Correct, I remember having a discussion about this last year.  We discussed a hacky way of implementing this by seeding the flow type and then checking after inference if it has been exceeded, but decided against it (I think?) because this wouldn't give a useful indication of where the error actually lies when there are multiple local contributions in the same grammar.  Not sure how hard this would be to implement the "right" way, but presumably not much more complex than flow specs for attributes were?

**Comment by tedinski** [comment]
Thanks for the reminder. I opened #238 for that.

**Comment by krame505** [comment]
This was fixed a while back with #617.
