### ISSUE TITLE
import ... with ... as ...; doesn't work for attributes

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#245]
No error is raised, but the attribute isn't renamed, either.  
Actually, this doesn't ever seem to raise an error if the renamed identifier is undefined; is this a bug, too?

**Comment by tedinski** [comment]
Not raising an error for unknown identifiers is a known limitation of how things work right now.

But, uh, `with ... as ...` works for me?

**Comment by krame505** [comment]
The specific case is where I do `import silver:langutil with pp as pp1;` but I still need to do `foo.pp` and not `foo.pp1` to avoid an error.  But just to be clear, is this the desired behaviour?  I guess the only case where this would actually be needed is if there are two different attributes with the same name that you want to occur on a single nonterminal.

**Comment by tedinski** [comment]
I'm still not sure how to reproduce the problem, exactly.

**Comment by krame505** [comment]
On further thought, I'm not actually sure that there is a problem.  I'm just trying to understand the intended behaviour here: 

```
import silver:langutil:pp with pp as pp1;
global e::Expr = ...;
global foo::Document = e.pp1; -- "Undeclared attribute pp1"
global bar::Document = e.pp; -- No error
```

**Comment by tedinski** [comment]
The intended behavior would be that it _should_ complain that `pp` is not a name exported by that grammar, but that's just slightly more difficult to do than it seems like it should be, and we never got around to it.

**Comment by krame505** [comment]
Ah, I forgot that `pp` is actually defined in `silver:langutil`... so I guess this works as I expected.  Closing this.
