### ISSUE TITLE
Add a grammar exporting host and all the default extensions/modifications

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#246]
Currently, artifacts for Silver need to duplicate the massive list of extensions and modifications used to build the parser.  This is a bigger deal now that we are going to start having lots of different composed versions of Silver.  It would be nice if we had a single grammar `silver:exthost` (or something like that) that exports `silver:host` and all of these, so that only one grammar needs to be included to get Silver with all the usual stuff.

**Comment by krame505** [comment]
Also, a total side-question, why is `silver:composed:Default` uppercase, violating our established grammar naming conventions?  Any reason not to refactor this at the same time?

**Comment by tedinski** [comment]
Refactoring the organization of the whole Silver compiler is probably on my todo list, if I get to it.

...and literally its because `default` is a keyword in Java. The choice of name comes from when Silver translated to Haskell.
