### ISSUE TITLE
Lazy reification

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#256]
One of the biggest downsides to using reify right now is that it is kinda slow for big trees.  However in some uses, such as serializing an environment, we are unlikely to actually use the entire tree.  A solution to this is to make reification lazy, and only reify a node if it is demanded.  

The biggest complication here is error checking, since we can no longer use the same exception chaining approach we used previously to trace the position of the error within the reified tree; the exception would now be thrown later from inside some thunk.  We can handle tracing by passing a new `ReifyTrace` object down through the recursion (I have already implemented this - see feature/lazyreify), but the problem still stands of how we report the error to the caller - to ensure that the entire provided `AST` is well-formed, we would need to compute the entire reification eagerly.  

I propose we add a new `reifyLazy :: (a ::= AST)` construct to the language, in addition to `reify`, but that may raise an exception if given an ill-formed tree.  This variant can be used in cases where a reification error is a fatal internal error anyway (such as for reconstructing the environment in Silver) and we don't really care too much how the exception gets reported.  

The implementation of this shouldn't be too complicated, we can simply modify the `Reflection.reify` function in the runtime to take a flag of whether to be lazy.  @tedinski thoughts on this?  I might try implementing it in the meantime.

**Comment by tedinski** [comment]
Hmm. I'm uncertain if the performance problem is coming from lack of laziness, and the error handling issue seems like a big one. How hard would it be to implement or prototype? Would it be painful if we ended up throwing away the implementation if it proved not to help performance?

e.g. could you just twist the current implementation to work lazily as a hack and see how it performs, as an experiment?

**Comment by krame505** [comment]
I've been experimenting with this and keep getting errors about not being able to cast `Thunk`s to various other types of objects.  What exactly are the rules about introducing laziness in Silver - where are `Thunk`s allowed to occur?  Simply returning a tree where children are `Thunk`s seems to break things.

**Comment by tedinski** [comment]
Children of productions (Node classes) and function arguments are exactly where Thunks are allowed, so not sure what problem you're having. (Sorta-kinda inherited attributes are like thunks too, but for historical reasons, those are Lazy objects that use `parent` instead...)

Is it a specific constructor? ConsCell should also accept thunks, but maybe terminals dont or something.

**Comment by krame505** [comment]
Thanks, seems the problem was actually that I was wrapping the entire body of `reify` in a `Thunk` and returning that, so calling `reifyLazy` would return a `Thunk` even at the top level.  

The result of this seems to improve the performance marginally, but it is hard to tell for sure due to the crashing bug I mentioned in #255.

**Comment by tedinski** [comment]
If the benefit is marginal, then we should maybe avoid this. Especially with the error reporting problem, I think strict reification is fine.

I'll try to take a look at the performance issue next week.

**Comment by krame505** [comment]
I'm not really sure what the performance benefit is, due to the random
crashing problem it's hard to experiment with updating and rebuilding more
than a couple of grammars.  That probably needs to be fixed before we look
too much at the performance.
Thanks

Lucas Kramer

**Comment by krame505** [comment]
Closing this since we decided not to go this route.
