### ISSUE TITLE
Thoughts on optimizing serialized interface files

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#260]
We have slick new serialized interface files thanks to #255 

But these are quite sub-optimal for the moment. The data structures weren't quite defined with serialization in mind, so we could likely benefit from actually looking at what's going on and changing things to work a little better.

Some preliminaries to improve things:

* [x] `GrammarProperties` could maybe become `InterfaceSpecs`? Still not sure about name.
* [ ] We don't need to `foldr` the list of these before serialization... we can do that after.
* [ ] There's a lot of `unparse` code that could now be removed. Not necessarily all of it though, some is in use by other things, oddly enough, I think...
* [ ] There are likely a lot of other odd choices, we need to look.

Here's a quick measure of what interface files now consist of:

```
$ grep -ho -P "[A-Za-z_0-9:]+\(" generated/src/silver/definition/core/Silver.svi | sort | uniq -c | sort -n | tail -n 20
    207 silver:definition:env:prodDcl(
    207 silver:definition:env:prodDclDef(
    235 silver:extension:list:listType(
    243 silver:definition:type:decoratedType(
    248 silver:definition:type:stringType(
    432 silver:definition:env:namedSignature(
    455 silver:definition:env:occursDcl(
    501 silver:definition:env:oDef(
    524 silver:definition:env:renamedEnvItem(
    526 silver:definition:type:terminalType(
    554 silver:definition:regex:regexSeqSnoc(
    622 silver:definition:regex:regexChar(
    672 silver:definition:regex:regexCharItem(
    708 silver:definition:regex:regexOnce(
    741 silver:definition:flow:ast:synEq(
    963 silver:definition:flow:ast:rhsVertex(
    998 terminal(
   2086 silver:definition:env:namedSignatureElement(
   2175 core:loc(
   2645 silver:definition:type:nonterminalType(
```

From this I immediately learned:

* [ ] There's almost certainly concrete syntax trees getting serialized, and we should fix that. I suspect it's the regexes. Not sure what to do about that. But `terminal` really shouldn't be high in this list. And `loc` should be lower, too.
* [ ] There's a ton of duplication: `prodDcl` and `prodDclDef` for instance. Along with a crap-ton of `renamedEnvItem` for each `DclInfo` that gets serialized. We could likely restructure the way `defs` in Silver get computed so this is less repetitive. And would probably just be an improvement to the environment code, too.
* [ ] My guess is that the reason `namedSignatureElement` and `nonterminalType` rank so high is because we duplicate production information between the "cstast" part and the "dclinfo" part. This would be hard to eliminate though.

Finally:

* [ ] Idea for general optimization: Hash-consing. The idea is to (statefully, within some operation) pay attention to all the sub-trees you've constructed so far, and whenever you find a repeated one, re-use the old one you already had. So:

1. Reflection can do this internally, to reduce the total number of `AST` nodes it creates in memory.
2. Serialization can do this internally, to emit a different format that numbers each subtree, and allows references to previously numbered subtrees.
3. Deserialization could then replicate the re-use of subtrees when it reads that format.
4. Reification could then pay attention to when it find a subtree it's already reified (maybe Java's `IdentityHashMap`), and re-use it.

This would:

1. Reduce file size. e.g. The "production has the location annotation" tree could appear only once instead of almost 200 times. All duplicated production signatures would appear only once.
2. Reduce dynamic type checking overhead. We'd eliminate all the duplicate type checking of each repeated subtree.

We'd probably have to hand-implement this serializer/deserializer in Java though. It'd no longer be ordinary parsing. So I suggest we not do this for a long time... the performance isn't too bad right now anyway.

**Comment by krame505** [comment]
Closing as I think #541 has sufficiently resolved the size/performance issues for the purposes of interface files.
