### ISSUE TITLE
occurs on with collection attribute

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#288]
It doesn't look like it's currently possible to add a collection attribute with `occurs on`.

**Comment by krame505** [comment]
```
synthesized attribute foo::[Integer] with ++;
attribute foo occurs on Expr;
```
works for me?

**Comment by tedinski** [comment]
I'm pretty sure he means in the same declaration.

```
synthesized attribute foo::[Integer] with ++ occurs on Expr;
```

**Comment by krame505** [comment]
This was fixed a while ago along with the addition of monoid attributes.
