### ISSUE TITLE
Lexer class modifiers should be comma seperated

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#299]
Currently terminal modifiers are comma-seperated and lexer class modifiers aren't.  This is inconsistent and should probably be fixed.  Any objections?

**Comment by krame505** [comment]
Currently there is `dominates {...}`, `submits to {...}`, `font = ...`, and now `disambiguate {...}`.  Previously this wasn't too noticeable of an issue because lexer classes typically don't have more than one modifier.  

@tedinski any thoughts before I go and change this?

**Comment by ericvanwyk** [comment]
How about allowing both?  Separate by comma or by nothing?  Then nothing breaks and new code looks nicer. Ted is out east snowboarding, so he may not reply soon.  In a few months we can go remove the separate-by-space option and see what breaks.

**Comment by krame505** [comment]
OK, I'll add the new version and deprecate the no-comma version for now in my feature/disambiguation_functions branch.  We can make the breaking change at some point in the future in another branch.

**Comment by ericvanwyk** [comment]
Sounds good.

**Comment by krame505** [comment]
It appears that this change is actually ambiguous- apparently, the dominates and submits to modifiers actually don't use braces, which we may also want to change for consistency.  For example
```
lexer class Cidentifier submits to Ckeyword disambiguate {...};
```
would become
```
lexer class Cidentifier submits to {Ckeyword}, disambiguate {...};
```
We could also consider making the braces optional for the common case of a single member of the submits to/dominates set, which would also aid backwards compatibility.  But since this is a bigger change, I'm going to leave it alone for now until I am done with disambiguation classes.

**Comment by ericvanwyk** [comment]
Makes sense to leave it for now.

**Comment by tedinski** [comment]
I looked into how things are actually used in practice, and it looks like the current syntax is only used in extremely special cases:

```
lexer class C dominates SINGLE_ID;
lexer class C submits to SINGLE_ID;
```

We can continue to accept these as special cases, and the freely modify the lexer class modifiers syntax to be more uniform with terminal modifiers. This should eliminate the parsing conflict, and allow backwards compatibility.

**Comment by krame505** [comment]
I'm finally getting around to fixing this now (along with several other fixes/enhancements to lexer classes and disambiguation.)  Note to self to close this issue when feature/lexerClasses gets merged.
