### ISSUE TITLE
Failing to initialize a collection production attribute results in a NullPointerException

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#322]
See title.  I ran into this using a collection production attribute of type `Maybe`, using `orElse` as the operator.  I don't have time to investigate this in more detail right now, but wanted to make a note of this for the future.  
Not a big deal since this is caught by the flow analysis, just kind of annoying.

**Comment by tedinski** [comment]
Minimal reproduction:

```
grammar missingeq;

function main
IOVal<Integer> ::= args::[String]  ioin::IO
{
  production attribute bad :: String with ++;

  return ioval(print(bad, ioin), 0);
}
```

Confirmed this only applies to production attributes, not any other kind of collection attributes.
