### ISSUE TITLE
Function type errors in arguments are wrong and confusing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melt-umn/silver#33]
```
This stems from the 'reverse' done on the type list.

Too many args, and all types will be reported wrong.
```

Original issue reported on code.google.com by `tux...@gmail.com` on 1 Mar 2013 at 9:50

**Comment by tedinski** [comment]
I'm going to add another note to this problem: when calling `doesNotExist(x)` we raise an error about `Too many arguments provided to function` when this should only be raised if we actually know how many arguments the function should have.
