### ISSUE TITLE
Automatically-derived terminal names are ambiguous

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#335]
The automatically-derived "human" terminal names implemented in #221 are awesome, except when Copper is reporting lexical ambiguities.  It is less than helpful to get an error message of the form
```
Unresolvable lexical ambiguity at parser states   [...] among terminals:
       ['table',edu:umn:cs:melt:ableC:concretesyntax:Identifier_t,'table']
```
as we don't know where the ambiguous 'table' keywords originated (what if 3 extensions defined a 'table' keyword?)  In this case it would be more helpful to have the full names of the terminals, as they would need to be included in the disambiguation function.  Not sure if this is something to fix in SIlver, or if we want to make Copper report both names when dealing with lexical ambiguities - e.g. something like
```
Unresolvable lexical ambiguity at parser states   [...] among terminals:
       ['table' (bogus_table:Table_t)
        edu:umn:cs:melt:ableC:concretesyntax:Identifier_t,
        'table' (edu:umn:cs:melt:exts:ableC:tables:concretesyntax:Table_t)]
```

**Comment by remexre** [comment]
I think I might need to fix this in Copper? I think I'll want to add an `<UnambiguousPP>'table' (bogus_table:Table_t)</UnambiguousPP>` to fix this; just using the `id` already present would give something more like:

```
Unresolvable lexical ambiguity at parser states   [...] among terminals:
       ['table' (bogus_table_Table_t),
        edu:umn:cs:melt:ableC:concretesyntax:Identifier_t (edu_umn_cs_melt_ableC_concretesyntax_Identifier_t),
        'table' (edu_umn_cs_melt_exts_ableC_tables_concretesyntax_Table_t)]
```

which is much less nice to read.

**Comment by krame505** [comment]
I was thinking that you could detect the ambiguities in Silver when generating the Copper spec.  But if fixing it in Copper is more elegant, then go for it.

**Comment by remexre** [comment]
Oh, as in generate a different `<PP>` when the grammar contains two terminals with the same pretty name? Yeah, that's actually a better idea; I'll do that and avoid messing with Copper.

**Comment by krame505** [comment]
Not just when there are two terminals in the grammar with the same pretty name - you can include terminals from different grammars in the same parser spec.

**Comment by remexre** [comment]
er yeah, that's what I meant
