### ISSUE TITLE
Overriding equations for globally propagated attributes

### ISSUE THREAD

**Issue by ericvanwyk** [melt-umn/silver#358]
(A few questions here were over on the Oberon0 repo, but they belong here.)

@ericvanwyk  asked "Can one override the behavior of a monoid attribute with explicit equations - for example, if an attribute for free variables propagates a list of names up the tree but on a let or lambda production one doesn't want the names bound in the production to propagate up?"

@krame505 responded "Currently overriding equations for globally-propagated attributes isn't supported. Mainly because I don't know of a straightforward way to implement this, and also allowing such overrides could be considered poor style: either an attribute is treated uniformly for a nonterminal and thus can be propagated globally, or it is treated specially for some productions and so we should be more explicit everywhere."

@ericvanwyk responds...  We should decide what we want first and then decide how to implement it.  I want to push back on this idea that we should not allow a production to override the default equations for globally propagated attributes.  I think free-variables is a good example for this.

But first, is generating aspect productions the only way to do this?  Could productions not also see that their left hand side nonterminal is decorated by a globally propagated attribute and thus insert the appropriate equation?  I'm not sure this is better and may be less obvious how to implement it but I'm wondering if it was considered.

I can buy the idea that if we say something is globally propagated then it is the same on all productions.  So how about an optional clause on the global propagate declaration of the form "except p1, p2, ..., pn" which says do not generate an aspect for these production?  It is then explicit where the global propagation doesn't happen.  This seems to fit with the principle of being concise but also explicit.

**Comment by krame505** [comment]
Fixed by #355.
