### ISSUE TITLE
Concrete syntax patterns are limited to matching on forwarding productions

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#362]
When translating concrete syntax patterns, we only ever look at the undecorated tree, which may contain forwarding productions, and the patterns we generate will match against these productions.
For example with ableC, the pattern `ableC_Expr { $Expr{a} + $Expr{b} }` with translate to `ableC:overload:addExpr(a, b)` and not `ableC:host:addExpr(a, b)`.  

For undecorated contexts (such rules in the reflection-based rewriting extension) this is the desired behavior.  However this is not typically the case when working with decorated trees, as matching directly on a forwarding production is essentially equivalent to writing a (possibly interfering) synthesized equation on a forwarding production.  In the case of `addExpr`, matching against the host production will look through the forwarding as expected when we see the overloaded version, while matching against the overloaded version would fail to match the host version if, for example, the overloaded version has been transformed away by a previous analysis.  

Since decorated pattern matching against forwarding productions as patterns is rather unusual, in ableC this issue mainly just arises with operator overloading.  In this case it would be possible to transform away the forwarding productions prior to reflection and meta-translation, using a functor attribute similar to `host`, while providing a dummy `env`.  This could potentially be done by a different variant of concrete syntax pattern literals, e.g. `ableC_host_Expr { ... }`.  

Also we may want to add a brief mention of this problem to the forthcoming reflection paper.  

Thoughts?

**Comment by ericvanwyk** [comment]
This is an issue with the reflection-based approach only?

**Comment by krame505** [comment]
After some further thought and discussion on this, the problem here is fundamentally that some abstract productions (e.g. `ableC:host:addExpr` lack a corresponding concrete production.

The most straightforward fix here is probably to introduce new concrete productions for these abstract productions as an "extension", and use transparent prefixes for disambiguation from the forwarding versions.  This approach allows for more flexibility (e.g. mixing host and forwarding productions in the same specification) then the alternative of optionally rewriting away the forwarding productions using functor attributes.

**Comment by krame505** [comment]
After trying this out in ableC I realized that we have the same problem with names as well- `directRefExpr` forwards to `declRefExpr` based on the environment.  This would require us to add a second version of identifiers and associated antiquote productions that are to be prefixed.  This should work but is slightly annoying.  

Alternatively we could make the non-overloaded versions the default and add prefixes for the (original) overloaded terminals.  I'm not sure it I like this very much either, though.

**Comment by krame505** [comment]
After poking at this a bit more I came up with a nice-ish workaround for the above issue with names.  We can add the production `PrimaryExpr_c ::= HostId_t id::Identifier_c` where `HostId_t` is a terminal with an empty regex.  This will never get parsed directly due to maximal munch, but we can still use a transparent prefix.  This lets us write things like
```
ableC_Expr { host::foo host::+ host::$Name{a} }
```
for the AST `host:addExpr(declRefExpr(name("foo")), declRefExpr(a))`
