### ISSUE TITLE
Type class design

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#364]
I thought we had an issue for this, but I guess not.  

This has been deferred for too long, and we are at the point where a lot of things would seriously benefit from having proper support for type classes.  This includes Dawn's implicit monad work, my work with term rewriting, and potential future development of Ted's work on randomized property testing.  Also there would be general benefits to the readability of Silver code (e.g. monoid attributes and do-notation wouldn't need to be parameterized by the monoid/monad instance functions to use, some common patterns could be made into generic utilities with type support for things like "anything with attribute pp", etc.)  I am considering taking a stab at this as a side-project this summer.  

A few thoughts/notes on this:
* Keeping things simple
  * We probably want to avoid as much of the complexity of higher-kind types as possible.  Require explicit kind signatures for type variables in constraints, maybe?
  * Maybe don't support default method implementations, at least initially.
  * We probably still want to eventually support chaining type classes into hierarchies, e.g. Functor -> Applicative -> Monad.  I don't think this itself adds much complexity.
* Quick syntax proposal:
```haskell
class Monad<m<*>> {
  bind::(m<b> ::= (m<b> ::= a) m<a>);
  pure::(m<a> ::= a);
}

instance Monad<Maybe> {
  bind = \ f::(Maybe<b> ::= a) Maybe<a> ->
    case a of just(x) -> f(x) | nothing() -> nothing() end;
  pure = just;
}

function seq
Monad<m<*>> => m<b> ::= x::m<a> y::m<b>
{ return bind(\ a -> y, x); }
```
* Attributes are themselves a restricted form of type class.  Once we have type constraints it should be straightforward-ish to support attributes in type constraints.  Presumably these constraints would need to include a (maximum) flow type.  For example:
```haskell
class Eq<a> {
  eq::(Boolean ::= a a);
}

inherited attribute isEqualTo<a>::a;
synthesized attribute isEqual::Boolean;
instance isEqualTo<a> occurs on a, isEqual {isEqualTo} occurs on a => Eq<a> {
  eq = \ x::a y::a -> decorate x with { isEqualTo = y; }.isEqual;
}
```
* As another example, `pp {} occurs on a` could be used in place of a `Show` type class.
* Standard library type classes can/should probably mirror Haskell, to a large extent.  Infix operators such as `==`,  `<>` and `>>=` can be made language extensions.
* Implementation: I haven't given this much thought yet.  Presumably #185 needs to get finished first.
* There is a connection between deriving for type classes and propagate for attributes.  For example instead of `deriving Eq` for a type, one might propagate the `isEqual` attribute.  In fact, we may not even need a seperate deriving mechanism that is specific to type classes.  This sort of custom `propagate` behavior probably makes more sense as something specified somehow in a Silver library rather than being a Silver extension specific to "equality" attributes, this needs more thought.

**Comment by krame505** [comment]
A few further thoughts:
* I'm not sure I like the angle brackets syntax for type classes, as these aren't really type "parameters" in the same way.  We probably don't have a reason to support multi-parameter type classes, anyway.  So maybe sticking with Haskell-style syntax of `Eq a` rather than `Eq<a>` would be cleaner.  
* Implementation: we need some form of run-time dispatching based on type.  This stands to benefit from the run-time type information we added for reify.  
* Every type class can translate into a Java interface, with an accessor method for every member of the type class.  Type class members with default implementations can be Java 8-style default methods.  A type class that derives from other type classes can translate to an interface deriving from those corresponding interfaces.
* Every implementation interface has a static list mapping runtime `TypeRep`s to instance objects for the interface.  When we need to get the instance value for a member of a particular type class at run time, we consult this list.
* The tricky part is where to get the run-time type in general when a type class member isn't a function that takes the instance type as a parameter.  For example with the Monoid type class, if I write a polymorphic function of type `(Monoid a => a ::= )` that just returns `mempty`, then how do we determine expected run-time type of `mempty` in order to dispatch?  This is the same issue that we encountered with `reify`.  There is an incomplete fix for this to pass around the extra required type information in https://github.com/melt-umn/silver/tree/feature/expectedType, but this gets messy.
* A potential stop-gap alternative that would still be somewhat useful is just to punt on this and not support type constraints.  This means that all dispatching would be static, and one could still write type classes that provide e.g. generic `bind` or `mappend` functions, but libraries would be somewhat more limited as we couldn't write functions over "anything that is a monad" for example.  However this limited behavior would still be useful for extensions (e.g. monoid attributes or do-notation) that would simply like to forward down to code that uses these operations with concrete types.  We also wouldn't have the same issues with type constraints for attributes, as these always dispatch at runtime on the tree itself.

**Comment by ericvanwyk** [comment]
These seem reasonable.  But at some point it will be good to separate out issue of concrete syntax, abstract syntax and semantics, and implementation issue.  The most important is abstract syntax and semantics.  The others are important and issues there may affect what we do with abstract syntax and the intended meaning of those constructs.  But our primary early focus needs to be on this.  I'd love to see some sort of AG calculus in which this work is done.  The tricky issues you mention with expectedType are things we should be careful about here - ideally something that we take our time to avoid.  Perhaps there will be other things in Silver that this is an opportunity to fix.

**Comment by krame505** [comment]
I agree, for the most part.

I'm not sure that this work fits into the context of some "AG calculus", though, if I understand what you mean by this.  Synthesized attributes themselves are basically a restricted form of type class, one for the type `a`, containing a single function with a parameter of type `a`.  So while there may be connections with attributes in that we also want to have attribute occurrences as type constraints or put type constraints in the types of attributes, type classes are really a more general concept than attributes that can't be translated away into attributes or something.  

Also a note on the implementation, I was doing some background research into how type classes work in Haskell, and found this very helpful document: http://okmij.org/ftp/Computation/typeclass.html
This describes the 3 main approaches that have been proposed for implementing type classes in a functional language.  The first method involves passing around a "instance dictionaries", similar to the instance objects that I previously proposed, as an extra parameter in the translation of functions with type class constraints - this would avoid issues with passing around an "expected type" everywhere.  The second approach is to perform a template-like specialization of functions for every possible type of instance used - this is probably not the most desirable approach for a number of reasons, such as making the already-large amount of code we generate even more so.  The third approach is based on dynamically checking types and dispatching, similar to what I originally suggested.

**Comment by krame505** [comment]
I'm splitting the syntax/semantics design and the implementation into seperate issues, as Eric suggested.  See #366.

In terms of semantics, I think we should mostly (to the extent possible) copy Haskell's behavior - although the syntax may differ, as outlined above.  The attribute and type class "worlds" are mostly orthogonal, besides potentially allowing attribute occurences as type constraints, however this is an enhancement that can be added after the initial implementation.  So I don't think there are really any big surprises here, as (undecorated) nonterminals and productions are pretty much the same as in traditional function languages.

**Comment by ericvanwyk** [comment]
While I agree that these two *worlds* may be orthogonal, it is the interaction between them that is the most interesting part of this, at least to me.  So I think we'd want this to be part of the initial effort.  I do agree that following Haskell is a good idea.  This might also give us some guidance on names, or at least prevent us arguing about this.  (Note, I still retain dictatorial veto power! :)

**Comment by krame505** [comment]
*From my email to Eric:*
There is a nice list of foundational papers on type classes at https://wiki.haskell.org/Research_papers/Type_systems#Type_classes.

The paper that originally introduced type classes was https://dl.acm.org/doi/abs/10.1145/75277.75283, this is a pretty good summary of most of the basic features of type classes in which we are interested. There is a fair amount of overlap with the other first few papers on that list.

Type classes and higher-kinded types (e.g. `Functor` and `Monad`): https://link.springer.com/chapter/10.1007/3-540-59451-5_4

Type classes and existential types (i.e. allowing type constraints on production signatures in our case): http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.54.755&rep=rep1&type=pdf
Not sure how useful this would be for us (in Haskell, it is stylistically preferred to put the type constraints on functions acting on a data type rather than directly on the data type constructors), but this should be straightforward to implement and might be good to include for completeness.

Haskell’s standard library was more of an ad-hoc iterative process, so I haven’t seen any good papers describing rationale for the current state of affairs. However a good reference is https://wiki.haskell.org/Typeclassopedia

Most of our use cases for type classes fall into the category of convenience, for example
* Inferring bind and return functions for do-notation
* Inferring append and empty for monoid attributes
* Inferring equality and ordering operations for standard library functions (`containsBy`, `sortBy`, `TreeMap` operations, etc.)
* The reify expected type problem could be solved by making `reify` a member of a `Reify` type class, and adding a deriving mechanism for this class.
`reflect` and `reify` could (in theory) be totally re-implemented using type classes without any need for runtime/foreign function stuff - this is more or less what the `Generic` type class in Haskell does. However there are few good reasons not to do this:
  * It is unclear how instances for such a `Generic` class could be derived that would handle unknown extension productions, without making this a modification and either altering the Silver build process or doing something in the translation, anyway.
  * Performance would probably be worse.
  * Good error messages for reify would be tricky without access to run-time type information.
* On the concrete syntax side of things, we could fix a few hacks related to typing of disambiguation functions if every lexer class was also a type class with the various terminal types as its instances.

Adding occurrence type constraints allows for a few further conveniences, such as
* Code cleanup by moving attribute accesses into helper functions, for example changing the type of `show :: (String ::= Integer Document)` to `pp {} occurs on a => String ::= Integer a`. Then we could just write `show(80, e)` instead of `show(80, e.pp)`.
* Proper typing for attribute sections, e.g. making `(.fst)` on `Pair` actually work (currently it is a “not yet implemented” error due to the presence of type variables.)

The most interesting bits are in the connection between Haskell-style derivable type classes (https://cyberleninka.org/article/n/425073.pdf) such as `Eq` or `Ord`, and attribute propagation. In particular the implementation of a propagated “equality” attribute may use an `eq` function provided by the `Eq` type class for leaf types on which the attribute does not occur. Conversely, the implementation of `derive Eq on NT;` might forward to something involving propagated attributes.

We might also want to introduce an `Arbitrary` type class for generating randomized trees for property testing in the future, if my thesis work ends up going in that direction. I don’t know exactly what deriving this would look like, yet, as the implementation would somehow need to handle potentially-unknown extension productions. This requires further thought.

One approach to implementing type classes is by leveraging run-time type information, but I don’t think we want to go in this direction. Doing so would require the expected type to be passed as an argument in lots of places in the generated code, and run-time type-based lookup would be less efficient than dynamic dispatch on an instance object, as I outlined in https://github.com/melt-umn/silver/issues/366. I don’t see this as a huge issue drawback though, as attribute/type class operations are generally separated from reflection-based operations, anyway. So while maybe less than perfect, it makes sense to me that we have two separate implementations for two different paradigms of generic programming.

**Comment by krame505** [comment]
Eric proposed that we include a new kind of type constraint to specify that a type is decorated, however on further thought I'm not sure that this is actually needed - one can write constraints about the attributes that occur on undecorated nonterminal type `a`, then use the type `Decorated a` in the definition of the function.

However due to our current notion of a fixed reference set, we still need some way of specifying this as a constraint for an undecorated nonterminal type.  

That leaves us with 3 kinds of type constraints related to attributes/decoration:
* Inherited occurs constraints (`inh occurs on a`): Indicates that `a` is an *undecorated* nonterminal type with the inherited attribute `inh` - i.e. one can provide an equation for `inh` on a value of type `a` and access `inh` on the same value, if such an equation exists.
* Synthesized occurs constraints (`syn {inh1, inh2, ...} occurs on a`): Indicates that `a` is *either a decorated or undecorated* nonterminal type with the synthesized attribute `syn` - i.e. one can access `syn` on a value of type `a`.  Additionally, the MWDA should check (when the constraint is checked for some concrete type) that
  * If `a` is an undecorated nonterminal type, the flowtype of `syn` on `a` does not exceed `{inh1, inh2, ...}`.  
  * If `a` is a decorated nonterminal type, the flowtype of `syn` on `a` does not exceed the nonterminal's reference set.  In this case the flowtype specified in the constraint is ignored.
* Reference set constraints (`decorate {inh1, inh2, ...} on a`): Indicates that `a` is an *undecorated* nonterminal type that includes `{inh1, inh2, ...}` in its reference set - i.e. one can access `inh1`, `inh2`, etc. (and all synthesized attributes constrained to occur on `a` with a smaller flowtype) on a value of type `Decorated a`.  Attempting to write the type `Decorated a` when `a` lacks a reference set constraint would be an error, for now.

A few observations:
1. Having to write e.g. `env occurs on a, typerep {env} occurs on a` seems redundant - I can't imagine a reason for having an inherited attribute in the flowtype of a synthesized occurs constraint, without actually being able to decorate the type with the inherited attribute.  So we probably should implicitly add inherited occurs constraints for all attributes listed in the flowtype of a synthesized occurs constraint.  This would allow one to just write `typerep {env} occurs on a` instead of the above example.  The same is probably true for reference set constraints.  
2. Reference set constraints should go away eventually once we change `Decorated` types to include an explicit flowtype - i.e. one would write `Decorated {env} Expr` or `Decorated {env} a` as a type, and `Decorated Expr` would be syntactic sugar for `Decorated {Expr's reference set} Expr`.
3. I don't think there is a reason to have a type constraint for the forward flowtype, since it doesn't make sense to pattern match on/write productions for an unknown type.  
4. I'm pretty sure that synthesized occurs constraints should hold for both the decorated and undecorated version of a nonterminal type - this is consistent with existing semantics.  
  4a. This allows us to give actual types to attribute sections (finally!)  E.g. `(.pp)` has type
    `pp {} occurs on a => (Document ::= a)`.  
    Attribute sections should be applicable to both decorated and undecorated trees.  
  4b. Note that (given observation 1 above) specifying a synthesized occurs constraint with a non-empty flowtype means that the constraint cannot be satisfied by decorated trees, because the synthesized occurs constraint would yield inherited occurs constraint(s) that in turn require the type to be undecorated.
  4c. A potential objection is that this would allow one to write type signatures like
    `unparse {} occurs on a => (String ::= Decorated a`)
    which would seem to imply the existence of a type `Decorated (Decorated a)`.  However this would be an error as in order to use the type `Decorated a`, a reference set constraint on `a` is required, which would in turn force `a` to be undecorated.

**Comment by krame505** [comment]
Should type classes be in the same namespace as types in Silver?  Classes and types share a namespace in Haskell, and it would be confusing to have types and type classes that share a name, anyway.  But on the other hand it never makes sense to give a type class where a type is expected, or a type where a type class is expected.  

The concepts are definitely related though - the "type" of a type class can conceptually be thought of as the type of the dictionary implementing the type class, and instances as values of that type.  But one would never actually use these types and values directly in a Silver specification.  

Thoughts?  @remexre @ericvanwyk

**Comment by remexre** [comment]
Rust used to have `fn() -> Tr` as valid syntax, but deprecated it in favor of `fn() -> dyn Tr` (and added `fn() -> impl Tr`, for existential quantification). I think they're still planned to be in the same namespace for forever though, to stop people from giving a type and a trait the same name.

I think we should probably disallow naming a typeclass and a type with the same name, unless there's a particularly compelling case; this frees us up to implement `ConstraintKinds` or something later if we want, but for now just saves us confusion. (Regardless of which we choose, there's currently nowhere in the syntax either a typeclass name or a type name would be legal, right?)

**Comment by krame505** [comment]
Yeah, that is basically my thinking.  

Keeping them in the same namespace complicates error checking a bit (since whenever we look up a name from that namespace we have to check that it is actually a type or a type class as expected) but also avoids the complexity of introducing another completely new namespace in the environment.

**Comment by ericvanwyk** [comment]
I think keeping them in the same name space makes sense too.

**Comment by remexre** [comment]
linking https://github.com/melt-umn/silver/issues/282 here; this would be especially nice if list syntax worked for any ListLike type. I think we'd probably want associated types for ListLike, though; maybe something like https://hackage.haskell.org/package/mono-traversable-1.0.15.1/docs/Data-MonoTraversable.html would be a good starting point for design?

**Comment by krame505** [comment]
Interesting. Makes sense in theory I think, but that would require either type families or functional dependencies, which I wasn't planning to implement in the immediate future. But this might be a reason to go down that path. Probably wouldn't be until after I look at attribute occurrence type constraints, though.

**Comment by krame505** [comment]
We would like to be able to write something like this as an instance:
```
instance Functor Either<a _> {
  myfmap = \ fn::(c ::= b) x::Either<a b> -> case x of left(l) -> left(l) | right(r) -> right(fn(r)) end;
}
```
however this doesn't currently quite work because lambda parameter types aren't generalized and can't contain new type variables - instead the body needs to be lifted into another global function:
```
function mapEither
Either<a c> ::= fn::(c ::= b) x::Either<a b>
{
  return case x of left(l) -> left(l) | right(r) -> right(fn(r)) end;
}
instance Functor Either<a _> {
  myfmap = mapEither;
}
```
This could be remedied with a variant of instance-binding that is combined with a function definition.  Does
```
instance Functor Either<a _> {
  myfmap fn::(c ::= b) x::Either<a b> = case x of left(l) -> left(l) | right(r) -> right(fn(r)) end;
}
```
seem like reasonable syntax?  

This is sort of connected with having more concise syntax for functions (don't think we have an issue for that?) since we want to be consistent with whatever we settle on for that syntax.  For example we might write something like
```
fun mapEither fn::(c ::= b) x::Either<a b> = case x of left(l) -> left(l) | right(r) -> right(fn(r)) end;
```
which I'm not 100% fond of, since there isn't an obvious place to add an optional signature for the return type.

**Comment by krame505** [comment]
There's kind of a weird case that I encountered in instance resolution that has to do with possibly-decorated types.  Consider the following:
```
nonterminal Foo;
instance Eq Foo {
  eq = ...;
}

synthesized attribute attr::Boolean;
production bar
top::Bar ::= a::Foo b::Foo
{
  top.attr = a == b;
}
```

This seems like it should work, right?  However type class instance resolution only happens *after* we have figured out the final types of `a` and `b`.  And at that point `a` and `b` are both still unspecialized: they have type `ntOrDecType(nonterminalType("Foo"), varType(_))`, which forwards to just `decoratedType(nonterminalType("Foo"))`.  So at instance resolution we instead look for an instance of `Eq Decorated Foo` and fail, rather than looking for the `Eq Foo` instance that exists.  The workaround is to write `new(a) == b` instead, which is slightly annoying but works.  

I'm not sure that there is a more elegant fix for this, unfortunately - to specialize based on the available instances, instance resolution would somehow need to happen twice and produce a substitution the first time.  And what if there was an instance for both `Foo` and `Decorated Foo`?  And most of the time, at least one operand is comparing with something that isn't a child, that has a more specific type.

**Comment by krame505** [comment]
It turns out that this is actually super annoying when dealing with generated code, since one has to conditionally generate calls to `new` in lots of places (e.g. `new(local1) == local2` to compare equality of undecorated trees, but only when these locals are in fact nonterminals.)  

So I took another look at doing this specialization based on contexts, and it turns out to not be quite as bad as I thought.  For now I'm only doing this on application of a name.  Currently this looks like:
* After we have type checked the applied expression and its arguments and computed some substitution;
* when some context exists on the name's type scheme that mentions a type we now know to be an `ntOrDecType` with the above substitution;
* if an instance of the context's type class exists  for the *un*decorated form of the type but _not_ the decorated form;
* _then_ specialize the `ntOrDecType` to its undecorated form.

Note that we still want to leave the type unspecialized if we determine that there is only an instance for the decorated form, since an unspecialized `ntOrDecType` gets treated as decorated anyway, and not specializing it may make for less confusing error messages (there would be an "unresolvable context for `Foo`" error rather than "got a `Decorated Foo` where a `Foo` was expected".)

It does still feel a little weird to me to be performing any sort of instance resolution to guide type inference, but I think in this limited case it makes sense.  And the resulting behavior is much less confusing to those uninitiated in Silver's semantics for possibly-decorated types.

**Comment by krame505** [comment]
It looks like getting occurs-on constraints on productions to work "as expected" with pattern matching will be very annoying.  For example,
```
inherited attribute isEqualTo<a>::a;
synthesized attribute isEqual::Boolean;
nonterminal Foo with isEqualTo<a>, isEqual;
production foo
top::Foo ::=
{ ... }

nonterminal Bar<a>;
production bar
attribute isEqualTo<a> occurs on a, attribute isEqual {isEqualTo} occurs on a =>
top::Bar<a> ::= x::a
{}

global res::Boolean =
  case bar(foo()) of
  | bar(x) -> decorate x with { isEqualTo = foo(); }.isEqual
  end;
```
seems like something that should work: the occurs-on contexts on `bar`'s child `x` are available when we match on `bar`.  

With regular type class contexts, this isn't an issue, because we only try and resolve constraints after type checking is finished.  But this poses a problem with occurs-on constraints, because the occurs-on determines the type of the attribute access, so we need to resolve occurs-on constraints during type checking and before producing a final substitution.  This  is currently a circular dependency mess because case expressions forward and compute environments (containing attribute occurs-on contexts!) based on type checking.  

This may be possible to straighten out, but would probably require some significant refactoring, and having occurs-on constraints work with pattern matching isn't all that important anyway - one can always just write an aspect production and attributes.
