### ISSUE TITLE
Origin tracking, strategy attributes, and bootstrapping

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#367]
Due to Silver being implemented in Silver, some care must be taken in the addition of any new "bootstrapped" feature that depends on its own implementation in some way.  Although git and Jenkins allow us to develop many minor features in parallel, we are effectively limited to having only one bootstrapped branch of development at any given time.  

It appears that the origin tracking and strategy attribute features of Silver have both become independently bootstrapped - i.e. the respective latest jars from these branches are required in order to rebuild them.  This will become a quite painful point in the future when we inevitably merge both branches into develop, as neither jar will be capable of building the merged code base.  

The strategy attribute extension in `feature/strategyattr` depends on itself in quite intricate ways, such that re-doing this bootstrap process from a build that doesn't support strategy attributes would be quite difficult.  I am less clear on to what extent the features of origin tracking are now being used within `feature/origintracking`, however.  Thus it seems to me that the easiest approach is to merge `develop` and `feature/strategyattr` into `feature/origintracking`, and make the required fixes/re-bootstrapping in that branch.  

We should hold off on merging either branch into develop for now, at least until we have a chance to make another release of Silver for the reflection COLA paper that does not include these features.  

@602p @ericvanwyk do you have any thoughts on this?

**Comment by 602p** [comment]
With respect to the bootstrapping question, the implementation of the OT stuff in `feature/origintracking` stuff isn't self-referential at all. That is you can build an OT-enabled `silver` in one step from a non-OT-enabled copy of silver. There's some shuffling that needs to be done to make it build a origin-tracked version of the standard library, then build the updated runtime against that. All this logic is encapsulated in the (gross) `./rebuild-for-child.sh` file in `feature/origintracking` which uses a "normal" silver compiler in `JARS-BAK` and produces an OT-enabled silver compiler and runtime.

That said, there has been enough feature drift between where `feature/origintracking` split off that it no longer works right with the latest jars from `fetch-jars` (it builds, but the changes in ignore terminal/layout semantics mean that the resulting compiler doesn't work right.) I'm merging the changes on `develop` back into `feature/origintracking`, which should make it build with the `develop` HEAD jars again. This leaves the question of how to bootstrap your strategy work open, but needs to happen anyway.

**Comment by krame505** [comment]
OK, that's good to hear.  

Presumably then `rebuild-for-child.sh` goes away once we are ready to merge this branch and commit to only tracked builds in the future?

**Comment by 602p** [comment]
It should, yes. That is, if the compiler + runtime jar that got fetched by `fetch-jars` was the OT-enabled one there would be no need for that script. The only reason for that script was to avoid becoming circularly dependent on some change I made by always rebuilding from a non-OT compiler. Not sure what our procedure is for "ABI" (Java API) breaking changes, but the OT stuff is one, so we need to figure out how that will work.

Also: I finished the merge, so `feature/origintracking` HEAD should be a clean patch on top of `develop` HEAD. This means you should™ be able to pull it down, pull the latest jars, and run `rebuild-for-child.sh` to get a working OT-enabled compiler.

**Comment by krame505** [comment]
Thanks.

Are you familiar with the process for updating the jars for a branch on Jenkins?  That would at least get rid of the build failure notifications.  Essentially you need to clone Silver and build the appropriate jars on coldpress.cs.umn.edu, run [this script](https://github.com/melt-umn/silver/blob/develop/support/jenkins/override_jars_path.sh), and then trigger a Jenkins build on your branch using the resulting path as the `OVERRIDE_JARS` parameter.

Also `feature/strattegyattr` is (presumably) stable at this point, and I expect us to merge that before `feature/origintracking`, so if you want you could preemptively merge `feature/strattegyattr` into `feature/origintracking`.  

I am planning to start work on implementing type classes in Silver at some point in the near-ish future, a feature that will presumably require breaking changes and significant modifications to the standard library/runtime.  I don't suspect that there will be too much trouble in merging this with origin tracking, however.
