### ISSUE TITLE
Reify can't handle Skolem types

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#368]
I thought there was an issue for this, but I guess not.  

The result type of `reify` must be inferred statically, meaning that `reify`ing into a Skolem type will always fail.  For example,
```haskell
function reify2
Either<String b> ::= x::AST
{
  return reify(x);
}
```
will always return `left(...)` because `b` is an opaque Skolem constant that unifies with nothing.  

The type of `reify` is static because while we can ask for the runtime type representation of a particular value, there is no general way of knowing at runtime the concrete type that an expression should return.  There is an incomplete attempt at passing around this extra type information everywhere at [feature/expectedType](https://github.com/melt-umn/silver/tree/feature/expectedType), but this was abandoned due to the resulting significant increases in overhead and complexity.  

The suggested alternatives (for now) are
* Make your function that calls `reify` a forwarding language extension to Silver instead
* Use `applyAST` (only possible in some cases)
* Do something with type classes (not yet implemented, coming soonish)

**Comment by tedinski** [comment]
Might be a good opportunity for a new warning or even error.

**Comment by krame505** [comment]
Yeah, @602p (Louis) is on it

**Comment by krame505** [comment]
Some thoughts on how we might actually fix this with type classes:
Essentially, we can introduce a type class `Typed` (or something) for things that have a run-time type representation.  This type class would have a method to get a run-time representation of this type.  `reify` would require there to be an instance of this type for its result; it would be an error to attempt to reify into a Skolem type lacking this constraint.  
Somebody could instead write the above function `reify2` as
```haskell
function reify2
Typed b => Either<String b> ::= x::AST
{
  return reify(x);
}
```
This would be quite similar in concept to passing around an expected type everywhere, except we would only pass it in the required places.  

There are 2 directions that we could go with implementing `Typed`.  
* We could make it a regular type class in the standard library, with special compiler support for deriving instances.  This means that we would need to bring in the run-time `TypeRep` representation of types as a foreign type, which kind of suggests that this type should be a regular nonterminal instead of a bunch of Java classes in the runtime.  This could be useful in other ways, but it would complicate the runtime and would probably have performance downsides.  The current mutation-based run-time unification approach probably wouldn't work with this change, either.
* We could make `Typed a` (or `typed a`) another kind of built-in type constraint, like the proposed occurrence and reference set constraints.  This is probably the simpler approach, but less flexible; the only property that you would gain through this type constraint is the ability to `reify` into that type.  The compiler would simply solve this constraint for any non-skolem type without an explicit deriving declaration. This "type class" could even be implemented by the `Typed` interface that already exists in the runtime.
