### ISSUE TITLE
Incorrect matching

### ISSUE THREAD

**Issue by RandomActsOfGrammar** [melt-umn/silver#371]
Consider the following match:
```
case left(3), left(4) of
| _, left(_) -> "right"
| left(_), _ -> "wrong"
end
```
The result of this should be `"right"`, but the result I am getting is `"wrong"`.

It appears that the clauses in the pattern matching are being compiled into a match in the wrong order.  I can look at this in the future, but I don't have the time right now.

**Comment by krame505** [comment]
Yep, that's a bug - good catch.  Beware, the pattern matching extension is a bit of a mess though.

**Comment by tedinski** [comment]
I'm surprised I didn't have an existing issue for this. There is at the very least a test with a comment, as I recall anyway.

The matching proceeds left-to-right instead of the expected top-to-bottom. This proved a very difficult thing to fix. I don't think the intermediate representation was amenable to it and never got around to refactoring.

Right now it's pulling off the first expression in the list and matching on that. Then the next, and so on, just iterating through the list. To get the expected semantics, you'd have to find the first expression such that the top-most match rule has a concrete case, then... transform everything in order to pull that "column" of matches out of all the lists. Or something to that effect.

Haha, look at this:

http://melt.cs.umn.edu/silver/ref/expr/pattern-matching/

> Compilation behavior (left-right, rather that top-bottom, maybe note this as known bug)

**Comment by RandomActsOfGrammar** [comment]
The way it should be compiled, I think, is to pull the non-default patterns in the leftmost column to the top, but add the matches in the rest of the columns from the initial default cases to the beginning of the rest of the existing patterns.  For example, the above match would be compiled into the equivalent of
```
case left(3) of
| left(_) -> case left(4) of
             | left(_) -> "right"
             | _ -> "wrong"
| _ -> case left(4) of
       | left(_) -> "right"
```
This puts the second clause's first pattern first, but adds the second half of the first pattern to its remaining clauses, so we get the right behavior.  I think this is what _The Implementation of Functional Programming Languages_ says, but I haven't looked at it lately.

This seems to be a little simpler than what you're suggesting, Ted, since we don't need to iterate over the columns and rearrange the order of matching.  How difficult it is to implement what I've suggested depends on how clauses are implemented.  If they are a list of single clauses, that would make it extremely difficult.  If it is a tree, it would probably be reasonably easy.  As I recall, the "correct" way to design collections in extensible languages is to use a tree structure to make forwarding easier.  Since we know everything in Silver is designed _so well_, it must be a tree structure, right?

**Comment by ericvanwyk** [comment]
It the behavior correct if you wrap it up in ``left(3), left(4)`` up in  ``pair``, as in ``pair( left(3), left(4))``?  Or is the sequence here not the issue?

**Comment by RandomActsOfGrammar** [comment]
The behavior is still wrong when wrapped in the pair.  This makes sense because it compiles into the same thing.

The initial match, written by the programmer, would be
```
case pair(left(3), left(4)) of
| pair(_, left(_)) -> "right"
| pair(left(_), _) -> "wrong"
```
This would be compiled into something like
```
case pair(left(3), left(4)) of
| pair(a, b) -> case a, b of
                | _, left(_) -> "right"
                | left(_), _ -> "wrong"
```
The compilation would then continue by translating the nested match into single-pattern matches.

**Comment by ericvanwyk** [comment]
Makes sense - just wanted to be sure. Thanks.

**Comment by tedinski** [comment]
> This seems to be a little simpler than what you're suggesting, Ted

Cool, that might work. It's been awhile. I think I was following a Wadler paper I can't remember the name of.

Thinking a bit, Wadler might have been going with the match-order-juggling approach to avoid duplication of the RHS expressions and such, to ensure code size doesn't blow up. That might be a downside with the simpler method? Maybe there's a fix for that, though.
