### ISSUE TITLE
Implicit monads give internal errors due to missing import of `core:monad`

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#389]
Currently forgetting to import the `core:monad` grammar can result in some errors in generated code that took me a while to figure out.  

I'm ok with waiting on fixing this though, as presumably all those monad functions will move to `core`/go away completely when we have type classes.

**Comment by krame505** [comment]
Whoops, opened this on ableC instead of Silver by accident.  Should be fixed.

**Comment by RandomActsOfGrammar** [comment]
I'm not really sure how to fix this.  I'm not sure there is a way to check this is imported in the extension.  Even if it can be checked, it would have to be checked on the equation productions, I think.  This would probably lead to the error for it showing up dozens or hundreds of times.

Maybe there is a way to force it to be imported, but I'm not sure what it is.  Type classes would allow it to simply insert a generic monadic operation, so we wouldn't need to rely on these functions anymore.

**Comment by krame505** [comment]
Yeah I added this as a marker issue, mostly.  Presumably when we add type classes the standard classes (including `Monad`, etc.) will move to `core` along with their instances and will be imported by default, and `core:monad` will just go away.  So I'm fine with not trying to fix this for now.

**Comment by RandomActsOfGrammar** [comment]
I believe this was fixed with the refactoring of `core`.
