### ISSUE TITLE
Higher-kinded polymorphism

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#398]
I've been thinking a bit more about how we would do higher-kinded polymorphism in Silver, needed for type classes such as `Functor` and `Monoid`.  Despite what I said in previous discussions, I think that types in Silver do need to be curried after all for this to work sensibly.  However perhaps we don't need type constructor kinds such as `(* -> *) -> *` - so I think that a "kind-arity" should suffice here rather than having a `Kind` nonterminal.  

For example, consider the `Functor` type class:
```haskell
class Functor f<*> {
  map :: (f<b> ::= (b ::= a) f<a>);
}
```
I am open to suggestions for better kind signature syntax, btw. `f :: (* ::= *)` would sort of mirror Haskell, but `(* ::= * *)` seems weird if types are curried.  

`Functor` has an instance for `Either`, where the left argument is any type and the right is the one over which we can map:
```haskell
instance Functor Either<a> {
  map = \ fn::(c ::= b) e::Either<a b> ->
    case e of left(x) -> left(x) | right(x) -> right(fn(x)) end;
}
```
The reason we would want currying can be seen in how this instance would be resolved.  For example in the following code:
```haskell
local foo :: Either<String Integer> = ...;
local res :: Either<String Float> = map(toFloat, foo);
```
we would infer the type `(Either<String Float> ::= (Float ::= Integer) Either<String Integer>)` for `map`.  This type would need to be unified with `(f<b> ::= (b ::= a) f<a>)` prior to instance resolution - `f<b>` needs to unify with `Either<String Float>`, giving substitutions `f ~> Either<String>, b ~> Float`.  I don't know how this could be done sensibly without currying.  

The representation of `Type` in Silver will need to change a bit to make this work
* A new production `apType :: (Type ::= Type Type)` will represent application;
* `nonterminalType` would change from `(Type ::= String [Type])` to `(Type ::= String Integer)`, containing an arity instead of a list of children;
* `varType` and `skolemType` will also need an arity attached: `(Type ::= TyVar Integer)`

`apType` would be translated as the translation of the type being applied, and an unapplied type of kind-arity > 0 should never show up in a place where a translation is demanded.  Note that the argument type of `apType` should also always have kind-arity 0.

I'm open to suggestions if anyone sees any potential pitfalls here that I may have missed - @remexre @ericvanwyk  @tedinski?

**Comment by remexre** [comment]
I don't know much about the implementation side, but this all seems reasonable from the user's side.

For syntax, this "looks more like normal silver" imo:
```
class Functor f::(* ::= *)
{
  function map
  f<b> ::= (b ::= a) f<a>;
}

class ListLike l
{
  type Elem<l>;

  attribute hd::Elem<l>;

  function filter
  l ::= (Boolean ::= Elem<l>) l
}
```

I think `(* ::= * *)` is fine as a kind signature, though if we're only supporting kinds like `* - > * -> *`, I would prefer `f<_>` to `f<*>` too.

**Comment by krame505** [comment]
I'm still trying to settle on a kind signature syntax.   `f<_>` is ambiguous with partial type application and `f<*>` is still a shift/reduce conflict, I think.  Using `::` for a kind signature (e.g. `f :: (* ::= *)`) is also a conflict since we don't know that we are parsing a `type :: kind` and not a `name :: type` until too late.  

So, any other ideas?  I'm open to anything at this point, but would prefer syntax that isn't a) horribly verbose or b) totally inconsistent with Silver and existing functional languages.  

@remexre @ericvanwyk

**Comment by remexre** [comment]
> Using :: for a kind signature (e.g. f :: (* ::= *)) is also a conflict since we don't know that we are parsing a type :: kind and not a name :: type in a function/production signature until too late.

Expand on this? Where do functions take arbitrary-kinded arguments?

**Comment by krame505** [comment]
Well, you could have
```
function foo
Functor f => f<Integer> ::= x :: f::(* ::= *)<Integer>
{ ... }
```
 as a part of a function signature, but since giving names to signature items is optional in Silver, you could also write just a type
```
function foo
Functor f => f<Integer> ::= f::(* ::= *)<Integer>
{ ... }
```
which would be a shift/reduce conflict.

But on further reflection, kind inference might be easier to implement than I was originally thinking, since we are requiring that all unapplied type arguments are provided as `_` in a partial application.  So I might just go that route, and skip on having kind signatures at all, for now.

**Comment by remexre** [comment]
yyyyyyeah requiring `f::(* ::= *)<Integer>` instead of `f<Integer>` qualifies as Very Surprising... Actually, if we always require enough arguments to lexically determine the kind, e.g.

```
function foo
Functor<f<_>> => f<Integer> ::= x::f<Integer>
{ ... }
```

That looks a bit more pleasing, and I think avoids the conflict.
