### ISSUE TITLE
Tuple syntax

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#399]
Eric pointed out that writing `Pair<String Integer>` in Silver is significantly more annoying than `(String, Integer)` in Haskell.  And more than 2 elements are even worse: `Pair<String Pair<Boolean Integer>>` vs. `(String, Boolean, Integer)`.  

We should add some nicer tuple syntax in Silver.  The easiest way to do this is probably inductively, such that `(a, b, c, d)` just forwards to `Pair<a Pair<b Pair<c d>>>`.  We would also want to add similar forwarding pattern and expression syntax: `(w, x, y, z)` forwards to `pair(w, pair(x, pair(y, z)))`.  

One could extract the members of a tuple via pattern matching or alternatively through the attributes on `Pair` (e,g, `.snd.snd.fst`).  Do we want to add more convenient syntax to access the nth member of a tuple?  Haskell doesn't have such syntax, but it is also possible there to immediately pattern match on a function argument or `let`-binding.  

Note that tuples in Haskell are *not* inductive, however the Bluespec language that I have been working on this year does do inductive tuples in this manner.  There is another side-benefit to this approach: one can write a type class instance for `Pair` and then automatically have instances for all tuple types.

**Comment by RandomActsOfGrammar** [comment]
I'm in favor of doing better syntax for pairs at least.  I think tuple syntax would also be nice to have.

I think if we're going to add tuple syntax, it would be nice to have a way to access elements without needing to write the pattern matching or a chain of `fst` and `snd`.  Off the top of my head, I have a couple of suggestions.

We could have a `get` attribute which takes an integer for the index to get.  The attribute access `p.fst` would be equivalent to `p.get(1)`.

We could have syntax which lets us write the index as if it were an attribute access.  For example, `p.fst` would be equivalent to `p.1`.  The index in general could be translated to `index - 1` `.snd`s followed by a `.fst`.

**Comment by ericvanwyk** [comment]
I'm not sure about doing this 'inductively'.  The types `(int * int) * int`, `int * (int * int)` and `int * int * int` are all different types.  I agree doing it this way is the easy way to have no limit on the size of tuples, but it does not seem correct to me.  I would suggest following Haskell here.

**Comment by RandomActsOfGrammar** [comment]
I believe Idris treats tuples inductively, so `(int, int, int)` is equivalent to `(int, (int, int))` and vice versa.  Therefore this behavior isn't *completely* unprecedented, but it could lead to some unintuitive behavior.

If we prefer Haskell to Idris, I think the best way to represent a tuple type would be for the tuple type to have a list of the types it contains.  This would let it be arbitrarily long, so we would get a unit type (zero types in the tuple) as well as standard tuples.

**Comment by krame505** [comment]
Consensus from our meeting today: inductive tuples are fine, try to make `,` just an infix type operator.  For selector syntax we are agreed on using `Expr '.' IntConst`, e.g. `a.1`.

**Comment by RandomActsOfGrammar** [comment]
I believe the issue of general tuple syntax was closed by #423.
