### ISSUE TITLE
Removing monto code

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#403]
As far as I know, the monto v3 code is dead at this point, and its runtime is no longer being built as of @602p 's origin tracking patch.  This would also need to move somewhere when we rename grammars/runtime packages as of #152.  Is there there a reason to postpone removing it?  

@remexre @ericvanwyk

**Comment by remexre** [comment]
removing it is fine by me

**Comment by ericvanwyk** [comment]
I suppose this is best.  But it makes me sad - it was better that LSP.  But LSP is probably the thing to use given its adoption...
