### ISSUE TITLE
Silver Eclipse should ship with additional library grammars

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melt-umn/silver#42]
```
We currently only ship core, ide, lib from the silver:grammars space.  We 
should also include silver:langutil as it has features that other languages 
besides Silver use.

Ming, please indicate here where the code is that does this.  I will try to 
change it myself.  I want to know where this code is in case this changes in 
the future anyway.

Thanks,
Eric

```

Original issue reported on code.google.com by `e...@umn.edu` on 31 Jul 2013 at 7:03

**Comment by tedinski** [comment]
Hey, @ericvanwyk I'm closing this old migrated issue. I had resolved it awhile back without realizing there was a related bug report. (Sort of: I dumped *everything* under `grammars` into what the IDE plugin carries with it now.)
