### ISSUE TITLE
MWDA is excessive with some error messages

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melt-umn/silver#43]
There are multiple situations where dual error messages are raised for a single error in the MWDA. These should be suppressed when it is safe to do so. (i.e. if we know the other error message will be emitted.)

For example, a missing equation on a production will be reported by both the production and the attribute occurrence, if both are in the same grammar.

We could determine that the production "is exported by" the occurrence, and decide to omit the error message on the part of the occurrence. (We should emit errors as close to the fix as possible, so biasing towards the production where we write equations is correct.)

**Comment by tedinski** [comment]
This specific issue is now resolved. I don't think there was another case of this?
