### ISSUE TITLE
Refactoring equality attributes

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#431]
This came up when discussing equality attributes with @remexre. 

We probably want to add some sort of "ordering attributes" that are similar to equality attributes but using the `<=` operator, for eventual use in deriving the `Ord` type class.  The inherited attribute in these that deconstructs the corresponding tree (`isEqualTo` in `equality attribute isEqualTo, isEqual;`) would be defined the same between equality and ordering attributes; additionally this type of attribute may be useful on its own.  Thus we may want to instead write
```
deconstruction attribute compareTo;
equality attribute isEqualTo with compareTo;
ordering attribute isLessOrEqualTo with compareTo;
```
This would be a fairly straightforward change.  I don't really like the name `deconstruction` though, any better ideas?  

Note that these are sort of an inherited counterpart to functor attributes: for example propagating `functor attribute foo;` on `addExpr` would give
```
aspect production addExpr
top::Expr ::= e1::Expr e2::Expr
{
  top.foo = addExpr(e1.foo, e2.foo);
}
```
while `deconstruction attribute bar;` would give
```
aspect production addExpr
top::Expr ::= e1::Expr e2::Expr
{
  e1.bar = case top.bar of addExpr(a, _) -> a | _ -> error("demanded when no match") end;
  e2.bar = case top.bar of addExpr(_, a) -> a | _ -> error("demanded when no match")  end;
}
```
Note that for the same values of the attributes on the children, the top value would be the same, except that the information flows in the opposite direction.

**Comment by ericvanwyk** [comment]
I'm not sure I understand the intention behind `deconstruction` attributes.  In the case of `bar` on `addExpr` - how is the equation for `e1` not just going to always give `e1` as its value?  When is `top.bar` not constructed by `addExpr`?

**Comment by remexre** [comment]
consider `x = addExpr(litExpr(2), z=litExpr(2))`, `y = addExpr(litExpr(2), litExpr(3))`:

`decorate x with { bar = y; }` would cause z to be decorated with `bar = litExpr(3)`

**Comment by ericvanwyk** [comment]
Ah, thanks. `deconstruction` is a bit of a mouthful.  How about `destruct attribute` ?

Does one ever need to write an explicit equation for one of these?

**Comment by krame505** [comment]
A `destruct` attribute would typically be used in conjunction with an `equality` or `ordering` attribute.  So if someone wanted to implement some sort of comparison that is not strict structural equality, then I suppose this could involve explicit equations for the `destruct` attribute as well.

**Comment by remexre** [comment]
If I understand it correctly (not having done a proper reading of this part of silver), if type unification were defined using a `destruct` attribute, `ntOrDecType` in particular would need equations... though for it to be symmetrical as it should be, so would `nt` and `decoratedType` and `varType`?

**Comment by ericvanwyk** [comment]
I wonder if a more intuitive specification of these would be 
```
equality attributes isEqual, isEqualTo;
```
that forwards to an `equality` and a `destruct` attribute declaration. This might be easier to explain.  It may lead to more `destruct` attributes than are needed.

**Comment by krame505** [comment]
Possibly.  The reason for separating these out is to allow for multiple operations that depend on the same `destruct` attribute to be evaluated on a tree at once without needing to evaluate multiple identical `destruct` attributes.  

Also I don't expect declarations of these attributes to be especially common - for the typical use case of comparing trees for equality/ordering, I expect
```
destruct attribute compareTo;
equality attribute isEqualTo with compareTo;
ordering attribute isLessOrEqualTo with compareTo;
```
to be declared in the standard library, with these same attributes being reused in most cases.  Of course for other use cases that don't exactly correspond to typical notions of equality/comparison, one could declare new attributes of this sort.

**Comment by ericvanwyk** [comment]
Yes, I understood the reason for separating them.  But the syntax I suggested is easier to explain.  I'm just looking ahead to papers or documentation about these kinds of things. On its own, `destruct attribute` is not an obvious thing - that's all I'm getting at.
