### ISSUE TITLE
Locations and antiquotation

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#434]
Generated code that makes use of antiquotation (e.g. `Silver_Expr { ... }`) uses the locations of the quoted source code as the locations of the constructed trees that are assembled at runtime.  Often this is useful in debugging, but is not the desired behavior in cases where we wish to check for errors in generated code.  

I described one possible fix for this in #425, using term rewriting to update the locations in the generated trees.  This is a bit of a hack unfortunately, and would result in somewhat of a hit to performance.  

This issue will also be solved by using origin tracking, however it may be awhile before we are ready to make the switch in Silver, and there is still some work needed to resolve how to still see the original source locations and flag errors in generated code when this is appropriate.  

As alternative for now, I propose that we add syntax to optionally specify a location to use in antiquote productions.  For example, one might write `Silver_Expr (top.location) { silver:core:eq($Expr{a}, $Expr{b}) )`.  This would be a fairly straightforward change in the `silver:compiler:metatranslation` library.  

Any thoughts/objections to this?

**Comment by ericvanwyk** [comment]
Why not just dive in and use origin tracking?  (Says the guy who would not be doing all the work this would involve and can thus be ignored...)

**Comment by krame505** [comment]
This should be fixed now by #803.
