### ISSUE TITLE
Concise function syntax

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#454]
Writing up what we have previously discussed.  

Currently functions in Silver are rather verbose, and every function has a production body such that it can define inherited equations on its arguments, define production attributes, can be aspected, etc.  This means that functions must be translated almost like productions.  90% of the time we don't need these features, and a more concise syntax would be desirable, e.g. instead of
```
function foldr
b ::= f::(b ::= a b)  i::b  l::[a]
{
  return if null(l) then i
         else f(head(l), foldr(f, i, tail(l)));
}
```
we might write
```
fun foldr b ::= f::(b ::= a b)  i::b  l::[a] =
  if null(l) then i else f(head(l), foldr(f, i, tail(l)));
```

This could be implemented as a pure extension if #453 is done:
```
global foldr::(b ::= (b ::= a b) b [a]) = \ f::(b ::= a b)  i::b  l::[a] ->
  if null(l) then i else f(head(l), foldr(f, i, tail(l)));
```
The translation of a lambda is more efficient than an ordinary function, since there is no need to create a decoration context.  This should also make @remexre happy for use with SilvIR.  

I am open to suggestions on improving the syntax.  Not sure where the return type would best fit, but we still do wish to allow for constraints, e.g.
```
fun mapFlipped Functor f => f<b> ::= x::f<a>  f::(b ::= a) = map(f, x);
```

**Comment by remexre** [comment]
Bikeshed: I'm not thrilled w/ the position of the return type; a very common search for me to do is "find every function/prod that returns something of type X," which is made way easier if that's the first or last thing on a line. tbh if we could output interface files to JSON, I could probably replace this usecase w/ `jq`, or even rig up some hoogle-like.

otoh, consistency is good, and everywhere else the return type is on the left...

**Comment by ericvanwyk** [comment]
What would we think of having two ways to write a function/production type?  By convention only, one would be used for productions and another be used for functions.  So
```
s::Stmt ::= cond::Expr body::Stmt
```
is the type of a while-loop production, for example.  And
```
fun foldr ( f :: (a, b) -> b, i::b, l::[a] ) -> b = case l of
  | [] -> i 
  | x::xs -> f (x, foldr (f, i, xs))
  end;
```
for `foldr`.  I'm not so sure about the `-> b` bit.  (But `-> foo` does give @remexre something to search for).

We can also think about using the tuple type syntax that @alexandra-hanson added to write `(Integer, Integer) -> Integer` for function types.

Again, the idea is that we have two synonyms for writing types - but a convention is used so that one variety is used for functions and another for productions.

**Comment by krame505** [comment]
@remexre how does having the return type at the beginning or end of the line make it easier to search?  I typically grep for e.g. `Expr ::=` which in my proposed syntax would still work.  

@ericvanwyk I feel like having two different syntaxes for function types would be even more confusing than just being "backwards" but consistent.  I also really don't like making function parameters comma-separated - even more so now that we have inductive tuples, which aren't really at all related to multi-parameter functions.  Also `-> b = ...` still doesn't put the return type at the end of the line anyway, if that is important.

**Comment by remexre** [comment]
oh, yeah, that'd work better :P I usually do `^Expr` for functions, `^[^:]*::Expr` for prods...

yeah agree with lucas

**Comment by ericvanwyk** [comment]
It isn't that I think having 2 kinds of syntax for types is a good idea, there are so many double colons floating around...

Regarding commas, this is something we got wrong at the very beginning with productions - signatures don't have commas separating args but applications of productions do. If we were starting from scratch this would be the thing I'd target first. But since we aren't (yet) starting over what you propose is fine.

**Comment by 602p** [comment]
My 2¢ is that evw's proposal seems pretty reasonable, although I don't like commas between arguments either. We could, in general, have `(foo::A bar::B) -> C` forward to `C ::= foo::A bar::B` and `(A B) -> C` forward to `C ::= A B`. Then it could be our convention to use the one for productions and the other for functions, but in a greenfield codebase you could do it as you chose. We could probably also do `= <BODY>` as a forward to `{ return <BODY>; }`. I don't know if that's the best way to implement it, but I think that would make sense as an extension.

That said, Nathan has a good point about searching. I often do search for (e.g.) `SomeType ::=` and would like to see all the places. Although I think the cases where I am looking for productions of a type and functions returning that type are disjoint, so grepping for `SomeNT ::=` in one case and `-> SomeType` in the other wouldn't be too bad. Although mixing them would be unfortunate. So if we do have an alternate syntax with the return type at the end for functions, we should probably do a full-tree search-replace for them to maintain greppability.

**Comment by remexre** [comment]
orrrrrrrrrrrr (annnnnnnd?) you could make docgen export json in addition to markdown, and I could write a bunch of hacky scripts in the short-term, and someone could port hoogle in the long-term, to get the search functionality

**Comment by krame505** [comment]
> We could probably also do `= <BODY>` as a forward to `{ return <BODY>; }`

One of the main reasons for adding this alternative function syntax is to *not* do it that way, actually, and instead forward to e.g.
```
global foo::(Integer ::= String) = \ s::String -> ...;
```
"Production style" functions involve creating a decoration context which doesn't matter for a function whose body is just an expression, since we aren't defining any attribute equations.  The current translation of lambda avoids this, allowing for a simpler and more efficient translation.  This would also make @remexre's life easier as the majority of existing functions could be transformed into this style where they would have an efficient translation in SilvIR, while the remaining functions that do set inherited attributes on arguments/define production attributes/etc. could be translated like productions.  

> (could be a cool shorthand to allow this for forwards, too.) I don't know if simple forwards are the best way to implement it, but I think that would make sense as an extension.

We actually almost never just write `{ forwards to ...; }` in a production body, usually there is at least an explicit equation for `pp`/`unparse` in the body, and often also some inherited equations.  So I guess I would be opposed to adding this syntax.

**Comment by 602p** [comment]
That's a very good point lucas, I retract that suggestion :). I still think that different/alternate function/production syntax is not unreasonable.

**Comment by ericvanwyk** [comment]
Thanks, Lucas - Part of the point of `fun` is to prohibit adding aspects on them.  And aspect can add a production attribute too, right?   What kind of error do we get if someone attempts to do this - thinking that `fun` syntax is just shorthand for the more verbose `function` syntax?

I'm glad that not everyone hates my idea about more reasonable function syntax. :)

**Comment by krame505** [comment]
If we have `fun` forward into globals, then the error would be the current error resulting from an attempt to aspect a global - "foo is not a function", which is less than perfect.  We could tweak this error message to be "foo is not an aspectable function" instead.

**Comment by ericvanwyk** [comment]
Make a note of it, but we can live with the current error message too.

**Comment by remexre** [comment]
ping @ericvanwyk

**Comment by unironically** [comment]
Implemented in https://github.com/melt-umn/silver/pull/819.
