### ISSUE TITLE
Renaming IO types/functions

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#461]
It is a little weird to have both the `IOMonad` and `IO`/`IOVal` types, and monadic duplicates of all the IO functions that are suffixed with `M` when we expect to be using these preferentially.  I don't think that it's advisable (or possible) to get rid of the primitive token-based IO, but we could consider renaming the `IO` type to `IOToken` and the `IOMonad` type to just `IO`.  Likewise `print` could become `printT` and `printM` just `print`.  

This would be a significant breaking change though, so I'm not 100% convinced that this is worth our time.  But if someone else is up for the task I wouldn't object.

**Comment by ericvanwyk** [comment]
I'd support doing this - and other things to make `main` and IO in general look nicer and be easier to do.  This would break everything but number of changes would be small - just a bunch of drivers.

**Comment by remexre** [comment]
Possibly nice to do at the same time -- now that we have a `Show` typeclass, it'd be nice to rename `print` to `putStr`, and have Haskell-like `putStrLn` and `print`.
