### ISSUE TITLE
Missing flow type checks on attribute sections (.attr)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [melt-umn/silver#47]
```
What steps will reproduce the problem?
1. map((.typerep), list :: [Expr]), where ft(typerep) = {env}
2. No errors or warnings
3. Crash!

We need to add checks for this.

```

Original issue reported on code.google.com by `tux...@gmail.com` on 18 Apr 2014 at 6:47

**Comment by tedinski** [comment]
Note to self:

The correct behavior here is probably:

1. For (Attr ::= Nt) sections, require the flowtype to be empty
2. For (Attr ::= Decorated Nt) sections, require the flowtype to be a subset of the ref set
