### ISSUE TITLE
Convenience aspects with a default case can still be incomplete

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#480]
```
aspect bagList2 on top::BazExpr of
| bazInit2(h::t,value) -> [h, toString(value)]
| coolName -> [coolName.hiddenAttr]
end;
```
is an incomplete match despite the default case, because the first thing has a nested pattern, and once it matches bazInit2 we are in the equation for a particular production, and don't have an option to fall back to a different one; thus the first case is flagged as an incomplete match, despite the default case.  

@ericvanwyk pointed out that in such situations we can duplicate the default case (if one is given) for the cases that are generated in each aspect production.  I think this seems fairly sensible, not sure how hard it would be to implement.

**Comment by RandomActsOfGrammar** [comment]
It shouldn't be too hard to implement.  I haven't looked at the convenience aspect code, but I assume it gathers all the patterns for a production and turns them into a `case` expression.  Adding the default simply requires also searching for a variable pattern and adding it to the generated `case` expression.

**Comment by hypnoticOxbow** [comment]
This change I think requires checking case completeness as we generate the case expressions for each aspect production.

If you have the following, for instance:

```
synthesized attribute gAttribute :: String occurs on BazExpr;
aspect gAttribute on BazExpr of
    | bazInit2(h::t,value) -> h ++ toString(value)
    | bazInit2([],value) -> toString(value)
    | bazInit3(h::t,val) -> toString(val)
    | coolName -> coolName.hiddenAttr
end;
```

which generates something like the following:

```
aspect production bazInit2
__generatedTop_372 ::= __generated_373::[String] __generated_374::Integer 
{
	__generatedTop_372.gAttribute = case __generated_373, __generated_374 of h::t, value -> h ++ toString(value) | [], value -> toString(value) end;
}

aspect production bazInit3
__generatedTop_375 ::= __generated_376::[String] __generated_377::Integer 
{
	__generatedTop_375.gAttribute = case __generated_376, __generated_377 of _, val -> toString(val) end;
}

aspect default production
__generatedTop_378::BazExpr ::=
{
	__generatedTop_378.gAttribute = let coolName :: BazExpr = __generatedTop_378 in coolName.hiddenAttr end;
}

```

Just inserting the output of the variable pattern into each will cause an overlapping case warning here (or it should, I'm having trouble making this cause an error atm):

```
aspect production bazInit2
__generatedTop_372 ::= __generated_373::[String] __generated_374::Integer 
{
	__generatedTop_372.gAttribute = 
      case __generated_373, __generated_374 of 
      | h::t, value -> h ++ toString(value) 
      | [], value -> toString(value) 
      | _,_ -> let coolName :: BazExpr = __generatedTop_378 in coolName.hiddenAttr  
      end;
}
```

Checking case completeness at the moment means the convenience aspects extension has to transform the `MatchRule`s it gets into `AbstractMatchRules`.

I initially wrote convenience aspects transforming the concrete MatchRules into AbstractMatchRules, but found this produced MWDA errors and it was suggested then that I rewrite it to work over the concrete MatchRules and produce concrete MatchRules as output.
