### ISSUE TITLE
Tuple selectors hide child errors

### ISSUE THREAD

**Issue by RandomActsOfGrammar** [melt-umn/silver#503]
This code should give an error, since `x` is an unknown name:
```
function fun
String ::=
{
  return x.1;
}
```
However, the `.1` seems to hide this error, so we end up getting an internal compiler error instead:
```
Internal compiler error: translation not defined in the presence of errors
```
We do not have this problem if we change the function body to
```
return x.fst;
```

**Comment by krame505** [comment]
It looks like `exprRef` suppresses the errors from the wrapped expression - I guess the assumption here is that the wrapped child is already type checked.  So `selector` would need to explicitly include these errors.  @alexandra-hanson do you want to take a shot at fixing this?

**Comment by alexandra-hanson** [comment]
@krame505 Yes, I will take a shot at fixing this soon.
