### ISSUE TITLE
Datatypes

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#556]
Datatypes, which are not nonterminals (like lists kinda sorta are).

- No forwarding
- No attributes (maybe reuse attribute syntax for UFCS?)
- No decoration
- Maybe Haskell-like syntax?

**Comment by krame505** [comment]
What does UFCS mean?  

I could maybe support an extension for more concisely defining a nonterminal and productions with no attributes with Haskell-like syntax, that just forwards to normal nonterminal/production decls.  But anything more than that seems like too much added complexity to be worthwhile.

**Comment by ericvanwyk** [comment]
Do define UFCS.

Would a "closed and we mean it" notion on nonterminal work?  This would be one where when you define, say, `List<a>` you can say it is closed so that no additional attributes from outside of this  grammar can be added.  If one doesn't define any attributes for it, then there are no attributes for it.

**Comment by remexre** [comment]
UFCS would basically be, we forward `x.f(y, z)` to `f(x, y, z)`.

I think the "it doesn't make sense to decorate this" is definitely part of what I want. "closed and we mean it" might work too, but even having built-in attributes feels potentially weird for e.g. a red-black tree -- the memory usage of operations on it should be stack usage, not heap usage.

**Comment by krame505** [comment]
If the goal is improving performance for specialized data structures, might I suggest another version of pattern matching that ignores forwarding?  

Introducing another category of nonterminals with different restrictions seems undesirable to me.  I don't see why the ability to decorate a `List<a>` or `Tree<k v>` with new attributes is particularly bad, if the commonly used operations were implemented efficiently as functions.  

https://en.wikipedia.org/wiki/Uniform_Function_Call_Syntax seems like a separate issue to me.  I could imagine maybe permitting it on nonterminals (we already overload dot notation for syn/inh/annotation...) but I would like to see some good example use cases first.

**Comment by remexre** [comment]
> I would like to see some good example use cases first.

Silver with #555:

```
sum(map(\xyz -> xyz.1.1 * xyz.1.2 * xyz.2,
        zip(map(\x -> (x, x + 1), filter(is_prime, foo)), bar)))
```

Silver with UFCS:

```
foo.filter(is_prime)
   .map(\x -> (x, x + 1))
   .zip(bar)
   .map(\xyz -> xyz.1.1 * xyz.1.2 * xyz.2)
   .sum()
```

Rust:

```
foo.iter()
   .filter(is_prime)
   .map(|x| (x, x + 1))
   .zip(bar)
   .map(|((x, y), z)| x * y * z)
   .sum()
```

Clojure's arrow macros (ported to basically every other Lisp) are basically the same idea, though implemented as a rewrite on the syntax. The Java Streams API, and (afaik) Ruby as well.

**Comment by krame505** [comment]
I'm going to start working on this now, as a dependency of #751.  For the moment, I'm going to implement `data` as another modifier on nonterminal declarations, alongside `tracked` and `closed`.  Nicer Haskell-style syntax, UFCS, etc. can be done in future pull requests.  

We would not permit inherited attributes to occur on `data nonterminal`s, or allow forwarding.  However I think we do want synthesized attributes that would be cached as normal, which would be useful for implementing some data structures like environments.  

A `data nonterminal` wouldn't be considered a "decorable type", thus we couldn't write `Decorated Maybe<Integer>`, but it would have a `DecoratedNode` created behind the scenes and cached on the `Node` if any synthesized attributes are accessed.  I think we might want to introduce a new `DataNode` class as the superclass of data nonterminal classes, to handle attribute accesses and wall off the things that aren't used like in `FunctionNode`.
