### ISSUE TITLE
production mcaseExpr_c in the implicit monads extension exceeds the allowed forward flow dependency set

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#611]
In the process of fixing all the flow errors in Silver, there are a few in the implicit monads extension.  One is that the `mcaseExpr_c` forwards depending on `mDownSubst` and `expectedMonad`, which are not in the allow forwards dependency set for `Expr`.

I think it should be possible to generate the translation without knowing the expected monad or monadic typing context, and only use those for computing `merrors`.

**Comment by RandomActsOfGrammar** [comment]
I put the wrong issue number in #619.
