### ISSUE TITLE
Deleting the Eclipse plugin 

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#685]
Since nobody is still using the Eclipse plugin (and it has actually been broken for a while now), we should delete it and the associated infrastructure:
* `grammars/silver/compiler/modification/impide`
* `grammars/silver/compiler/composed/idetest` and equivalent in silver-ableC
* `runtime/imp`
* `resources/ide_skeleton`
* `make-ide` script
* Font declarations on terminals in Silver, ableC and other projects

**Comment by ericvanwyk** [comment]
Yes!
