### ISSUE TITLE
Java error from production changes in concrete syntax

### ISSUE THREAD

**Issue by RandomActsOfGrammar** [melt-umn/silver#713]
Adding or removing a production in a concrete grammar is giving me a number of errors like this:
```
grammars:
    [javac] Compiling 197 source files to /home/micha576/research/melt/silver/generated/bin
    [javac] Ignoring source, target and bootclasspath as release has been set
    [javac] /home/micha576/research/melt/silver/generated/src/ComScaN/host/concreteSyntax/Pp_ComScaN_host_concreteSyntax_Concrete_sv_105_0.java:22: error: cannot find symbol
    [javac]     public static final int num_local_attrs = Init.count_local__ON__ComScaN_host_concreteSyntax_p_ComScaN_host_concreteSyntax_Concrete_sv_105_0;
    [javac]                                                   ^
    [javac]   symbol:   variable count_local__ON__ComScaN_host_concreteSyntax_p_ComScaN_host_concreteSyntax_Concrete_sv_105_0
    [javac]   location: class Init
```
Removing the generated Java sources in the Silver `generated` directory fixes this, so I suspect it is not correctly detecting changes to the grammar and trying to reuse out-of-date code.

I have not seen this error without having equations for abstract syntax trees in the productions.

**Comment by krame505** [comment]
Seems like some source files aren't being deleted when re-translating a grammar?  Not sure how that is possible.

This only happens when the production is concrete?  And the error happens when adding a production as well as removing it?

If that is the case, I might need to see the complete before/after code in order to debug.

**Comment by krame505** [comment]
I ran into the issue myself and I think I figured it out - we had the wrong path in deleting old source files, so we weren't actually deleting anything.  I don't see how this issue could happen when adding a new production, though.
