### ISSUE TITLE
IO monad repeats actions

### ISSUE THREAD

**Issue by krame505** [melt-umn/silver#78]
I'm not sure how nobody managed to notice this yet, but the IO monad appears to be repeating actions.  For example, calling runIO on the following
```
do (bindIO, returnIO) {
  printM("A\n");
  printM("B\n");
};
```
causes
```
A
A
B
```
to be printed.  Removing the ```unsafeTrace``` call for the equation for stateOut in bindIO prevents this from occuring.

**Comment by tedinski** [comment]
Ohohohoho!

This is issue #8 popping up and roaring.

**Comment by tedinski** [comment]
Fixed with #91.

**Comment by krame505** [comment]
Glad to see this is finally fixed!  Has anyone checked that the monad
driver for ableC now runs correctly (without printing errors, etc. more
than once?)

Lucas Kramer

**Comment by TravisCarlson** [comment]
Hi Lucas,

Yes, I've been verifying this against ableC and it no longer prints in duplicate. Though if you could also verify and let me know if you still notice any problem, that would be great.

Thanks,
Travis

**Comment by tedinski** [comment]
Ah, good call. I closed it assuming this would fix it. We should ofc verify.
