### ISSUE TITLE
Specification of prefix separator in parser spec doesn't override one in host.

### ISSUE THREAD

**Issue by ericvanwyk** [melt-umn/silver#85]
Specifying a prefix separator inside a parser specification doesn't override the one specified in the host language.  Instead an error is raised stating that there are two prefix separators specified.

I think a nicer behavior would be to have the parser spec one take precedence.

**Comment by krame505** [comment]
I would consider this an actual bug, not an enhancement, since the current behavior is not the intended one.  

To fix this, I think the contents of the parser spec would need to open a new scope with the module exported defs generated from the liftedAGDcls from the body.

**Comment by ericvanwyk** [comment]
I marked it as 'enhancement' since the intended behavior was probably never
precisely laid out.  Also, things work pretty well now - at least for the
ableC demos that I'm concerned with.

We should address this eventually, however.
