### ISSUE TITLE
Install Guide out of date

### ISSUE THREAD

**Issue by TravisCarlson** [melt-umn/silver#88]
I created a [doc/install](https://github.com/melt-umn/silver/tree/doc/install) branch and started replacing references to Mercurial / Google Code with Git / Github. Before creating a pull request, I have some questions about how we want to present Silver to first-time users.

The latest release was pointing to the [Downloads](http://melt.cs.umn.edu/silver/downloads.html) page (on the old website), which just pointed to the repo, so I changed it to point to the Github [releases](https://github.com/melt-umn/silver/releases) instead. These aren't the same as the tarballs at /web/research/melt.cs.umn.edu/downloads/. The Github releases contain the full source and no jars so the instructions would need to be updated to mention `fetch-jars`. Should the instructions assume everyone builds from "the bleeding edge from version control"? Or do we want to recreate a _Downloads_  page on the new website?

The [latest development build](http://melt.cs.umn.edu/downloads/silver-dev/silver-latest.tar.gz) doesn't appear to be the latest so I removed the link to it. Again, is this something that we still want to provide (maybe generate it with Jenkins now that it is up again?)  or do we only want to point to the repo?

Has it been 3 years since the last release? What's the criteria for a new release that's not being met? I understand our users seem to be comfortable running and updating everything from a cloned repo but, if nothing else, having a more recent release would look better presentation-wise to new users. When I see a project that hasn't had a release in so long my first thought is it's either 1) extremely stable, 2) dead, or 3) was previously stable but is now hopelessly broken. I don't think any of these apply to Silver. Silver seems to me to be much more stable and usable than anyone appears to give it credit for.

Ted, I know you weren't enthusiastic when I mentioned the idea of creating a Silver RPM (again, possibly automated by Jenkins.) Are you against the idea or just indifferent? I'd like to look into it. Even if it ends up not being used by the people who user Silver most, as a first-time user it would be nice to just install(/uninstall) a package that gives me a `silver` command to run from the command line.

**Comment by ericvanwyk** [comment]
Travis, thanks for looking into this and, hopefully, prodding us to get a
more proper release strategy set up.

I agree with your comment about needing a release for PR reasons.  We
should do this before the end of summer.

Whenever we merge `develop` into `master` we should create a proper
release.  On the melt.cs.umn.edu web page we need tarballs with jars in
them.  It should be as dead simple as possible to grap it and go.  There
should be a 'downloads' page here with good instructions.

If GitHub 'releases' are only the source snap-shots when a release is made,
that is fine, as long as it is clear that 'fetch-jars' needs to be run.

We should write instructions assuming people don't build from the develop
branch.  Providing some instructions for doing that seems OK too, but we
shouldn't assume this.

Criteria for release....?  Hmm.  We've just been lazy with this.  We need
to get this ball rolling again.

I'm also not enthusiastic about an RPM - it is just one more thing for us
to maintain and we don't exactly have a huge user community.  But if you're
keen, then I'm not opposed.  But if we do an RPM then we should do a Mac OS
X 'brew' distro as well.  I think these are just Ruby scripts, so probably
not too hard.  But I think this is rather low priority.

Take a look at the make-dist (or something similarly named) in the Silver
repo and see if this would do what needs doing.

-Eric

**Comment by tedinski** [comment]
Ah, good. The website in general needs work since google code closed down.

> Or do we want to recreate a Downloads page on the new website?

This is what we should do.

> The latest development build doesn't appear to be the latest so I removed the link to it. Again, is this something that we still want to provide (maybe generate it with Jenkins now that it is up again?) or do we only want to point to the repo?

It should have been relatively latest, no? Jenkins only went down a few weeks ago I thought. Unless something broke awhile ago and no one noticed.

> Has it been 3 years since the last release?

Oi. There's actually a bug related to the MWDA that I've been meaning to fix before a 0.4 release. That's most of what's holding that up.

> Ted, I know you weren't enthusiastic when I mentioned the idea of creating a Silver RPM (again, possibly automated by Jenkins.) Are you against the idea or just indifferent?

I mean, it doesn't hurt me at all, I just think it wouldn't be useful. It changes often and requires sysadmin to install.

**Comment by tedinski** [comment]
Think this is mostly taken care of, except making the release...
