### ISSUE TITLE
Enhancing our Jenkins CI stuff

### ISSUE THREAD

**Issue by tedinski** [melt-umn/silver#94]
We'd like to trigger builds on commits to any branch, and have Jenkins report the health of that change, before we actually cause the build to happen. Currently Jenkins is only tracking 'develop', and that's without doing upstream notification that things succeeded.

I've been experimenting with this here: https://github.com/melt-umn/test

Here are the current problems:
1. Jenkins does not properly set properties for the project on first run. This means if we take build parameters, the script crashes when it attempts to access them (instead of getting defaults.) This is probably not a blocker, it's just annoying and evidence of poor quality. (https://issues.jenkins-ci.org/browse/JENKINS-35698)
2. Jenkins does not visualize parallel steps within a pipeline. So we if try to build a "build silver -> run each test suite in parallel -> etc" pipeline, we'd only see "a failure happened" on the testing stage. Not which suite failed. (This is in progress: https://issues.jenkins-ci.org/browse/JENKINS-33185) This is probably not a blocker, since we can just run all the tests locally. But it'd be nice to know, darn it.
3. Worse, it's hard to find the console output of just one of a parallel set of tasks. The output is otherwise either interleaved or annoying to look at. (https://issues.jenkins-ci.org/browse/JENKINS-27394 I think. This isn't explicit, but it's the only jenkins bug I've found referencing this issue.)
4. Jenkins has astoundingly confusing workspace allocation behavior. ~~It appears to be possible for concurrent builds to step on each other's workspaces. This is just... WTF.~~ There doesn't seem to be a way to make pipeline builds disable concurrency, either. (Here's the bug for prevent concurrency: https://issues.jenkins-ci.org/browse/JENKINS-25638.)  (WAIT: I just re-ran a previous test and saw different behavior, so perhaps we're actually okay with concurrency and I made a mistake in figuring out what was going on. In any case, it seems to aggressively re-use the "default" workspace for a job (including its previous contents!), but this leads to unexpected behavior when it doesn't. When writing Jenkinsfiles, note that every `node` could be in a different workspace (even if it isn't always) and learn to use `stash` and `unstash`.)
5. The `stage` step seems to be a in flux, and this just confuses me. (https://issues.jenkins-ci.org/browse/JENKINS-26107) I appear to be doing things the "old" way. There appears to be some concurrency something or other about it. The documentation is not up to date, and the intentions are not clear about the behavior of this. (This seems to suggest doing things the new way: https://github.com/jenkinsci/pipeline-examples/blob/master/docs/BEST_PRACTICES.md so I guess I should update to do that.)
6. I've presently had to disable builds triggered on pull requests that _are not branches in our repository_ already. There appears to be no security on this at all. (There are two steps to re-enabling it: alter the configuration of the `melt-umn` job that scans the github organization. And alter the organization's webhook configuration to notify for pull requests.) I can't find any jenkins bug filed about this issue. Search keywords: multibranch pipeline pull request public untrusted

Okay, all that said, I think we can build something that works here. But my initial enthusiasm for how much nicer the Jenkins 2.0 pipeline stuff is has worn off a bit. It's got good bones, but there's been a couple odd decisions, and there's a lack of polish..

**Comment by tedinski** [comment]
Question: How do we indicate up/downstream relationships? E.g. build a separate ablec extension repo whenever ablec changes? (Presumably, without having to modify ablec to say so.)

**Comment by remexre** [comment]
2, 3, 4, and 6 get fixed if we migrate to Travis CI, which should be rolled out "soon."

This doesn't fix inter-repo dependencies, which Travis doesn't formally support, although we could either:
 - Hack a test hook together that forces a rebuild of repoB, repoC, etc. whenever repoA passes a build. Easy to write?
 - The same, but make it a post-build step of repoA's build process (i.e. in the script). Potentially more stable.
 - Make one of the sub-job-things of repoA's build process, so repoA doesn't pass unless repoB and repoC do too.

Slack notifications, GitHub integrations (for each commit and for PRs) and Artifactory (or melt.cs.umn.edu) deployment are also easy (and defined by config file in repo, not by settings in WebUI).

Once this is rolled out, I'll play around with it a bit; it shouldn't be hard to get it building.

**Comment by tedinski** [comment]
I wasn't too enthused with travis-ci last I looked at it.

I don't recall everything, but we have tricky things to do with artifacts. We build silver with the last known good jars, then we rebuild all our projects with those jars, before publishing them as the new last known good jars.

Jenkins has its own issues, but so far it seems like the least terrible solution.

**Comment by remexre** [comment]
I know it's possible to do "last known good jars", by having Travis not manage them -- you'd have it deploy the JARs to another place (e.g. melt.cs.umn.edu, Artifactory, etc.) on success, then fetch them for the next build as a prebuild thing. The third of the inter-repo "reverse" dependency suggestions should be able to handle the ensuring that everything's happy and healthy before deploying.

**Comment by tedinski** [comment]
Closing: Jenkinsfile introduced with #215
